import type { Metadata } from 'next';
import ServicesContent from './ServicesContent';

export const metadata: Metadata = {
  title: 'Services | MyEnum Agency - Software Development, Web & Digital Marketing Services',
  description: "Explore Myenum's professional services: custom software development, web development, mobile app development, SaaS products, e-commerce solutions, and digital marketing services. 500+ projects delivered globally.",
  keywords: [
    'Myenum services',
    'services',
    'our services',
    'software services',
    'web services',
    'digital services',
    'development services',
    'IT services',
    'web development',
    'website development',
    'custom web development',
    'professional web development',
    'web development services',
    'website design',
    'website designing',
    'website design services',
    'custom website design',
    'professional website design',
    'software development',
    'custom software development',
    'enterprise software development',
    'software development services',
    'business software development',
    'mobile app development',
    'mobile application development',
    'iOS app development',
    'Android app development',
    'cross-platform development',
    'hybrid app development',
    'mobile app services',
    'app development services',
    'SaaS development',
    'SaaS product development',
    'SaaS application development',
    'cloud SaaS development',
    'SaaS platform development',
    'e-commerce development',
    'e-commerce website development',
    'online store development',
    'ecommerce website',
    'shopify development',
    'woocommerce development',
    'magento development',
    'digital marketing services',
    'digital marketing',
    'online marketing',
    'internet marketing',
    'SEO services',
    'search engine optimization',
    'local SEO',
    'national SEO',
    'international SEO',
    'SEO company',
    'SEO agency',
    'SEO expert',
    'PPC services',
    'Google Ads management',
    'PPC advertising',
    'Google Ads',
    'Facebook Ads',
    'Instagram marketing',
    'social media marketing',
    'social media management',
    'LinkedIn marketing',
    'YouTube marketing',
    'content marketing',
    'content strategy',
    'content creation',
    'email marketing',
    'email marketing services',
    'video marketing',
    'influencer marketing',
    'digital advertising',
    'online advertising',
    'lead generation',
    'conversion optimization',
    'CRO',
    'marketing automation',
    'UI UX design',
    'user interface design',
    'user experience design',
    'graphic design',
    'logo design',
    'brand identity',
    'branding services',
    'web design services',
    'mobile app design',
    'prototype design',
    'wireframe design',
    'API development',
    'API integration',
    'backend development',
    'frontend development',
    'full stack development',
    'database development',
    'cloud development',
    'AWS development',
    'Azure development',
    'Google Cloud development',
    'cloud computing',
    'cloud services',
    'DevOps services',
    'IT consulting',
    'software consulting',
    'digital consulting',
    'technology consulting',
    'business consulting',
    'consulting services',
    'maintenance services',
    'software maintenance',
    'website maintenance',
    'support services',
    'technical support',
    'IT support',
    'helpdesk services',
    'QA testing',
    'software testing',
    'quality assurance',
    'test automation',
    'security testing',
    'penetration testing',
    'cybersecurity services',
    'IT security',
    'data security',
    'blockchain development',
    'AI development',
    'machine learning development',
    'ML development',
    'artificial intelligence',
    'IoT development',
    'data analytics',
    'big data',
    'CRM development',
    'ERP development',
    'custom CRM',
    'custom ERP',
    'business automation',
    'workflow automation',
    'process automation',
    'inventory management',
    'accounting software',
    'hospital management software',
    'clinic management software',
    'doctor software',
    'healthcare software',
    'education software',
    'real estate software',
    'logistics software',
    'manufacturing software',
    'retail software',
    'restaurant software',
    'hotel software',
    'appointment booking',
    'project management',
    'consultation services',
    'free consultation',
    'project quote',
    'get quote',
    'request quote',
    'digital transformation services',
    'business solutions',
    'technology solutions',
    'innovation services',
    'startup MVP',
    'MVP development',
    'minimum viable product',
    'startup development',
    'prototype development',
    'product development',
    'digital product',
    'software product',
    'web product',
    'app product',
    'platform development',
    'portal development',
    'web portal',
    'dashboard development',
    'admin panel development',
    'cms development',
    'wordpress development',
    'drupal development',
    'joomla development',
    'react development',
    'angular development',
    'vue development',
    'next.js development',
    'node.js development',
    'python development',
    'django development',
    'flask development',
    'java development',
    'spring development',
    'php development',
    'laravel development',
    'codeigniter development',
    'ruby development',
    'rails development',
    'golang development',
    'rust development',
    'swift development',
    'kotlin development',
    'flutter development',
    'react native development',
    'digital solutions',
    'end-to-end solutions',
    'comprehensive solutions',
    'complete services',
    'full stack services',
    'one-stop solutions',
    'all-in-one services',
    'service provider',
    'service company',
    'development provider',
    'software provider',
    'technology provider',
    'outsourcing services',
    'offshore services',
    'dedicated team',
    'staff augmentation',
    'nearshore development',
    'India services',
    'global services',
    'worldwide services',
    'international services',
    'Salem services',
    'Chennai services',
    'Bangalore services',
    'Hyderabad services',
    'Mumbai services',
    'Delhi services',
    'Kerala services',
    'Coimbatore services',
    'Dubai services',
    'UAE services',
    'USA services',
    'UK services',
    'global clients',
    'international clients',
  ],
  openGraph: {
    title: 'Services | MyEnum Agency - Software Development, Web & Digital Marketing',
    description: "Explore Myenum's professional services: custom software development, web development, mobile apps, SaaS products, e-commerce solutions, and digital marketing.",
    url: 'https://myenum.in/services',
    siteName: 'MyEnum Agency',
    images: [
      {
        url: '/iconc.webp',
        width: 1200,
        height: 630,
        alt: 'Myenum Services - Professional Software Development',
      },
    ],
    type: 'website',
    locale: 'en_IN',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Services | MyEnum Agency - Software Development, Web & Digital Marketing',
    description: "Explore Myenum's professional services: custom software development, web development, mobile apps, SaaS products, e-commerce solutions, and digital marketing.",
  },
  alternates: {
    canonical: 'https://myenum.in/services',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function ServicesPage() {
  return <>
  <ServicesContent />
  </>;
}