// app/layout.tsx
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { ClientLayout } from "@/components/ClientLayout";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const jetbrainsMono = JetBrains_Mono({ variable: "--font-jetbrains-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyEnum Agency | Best Software Development Company India & Global",
  description:
    "Top-rated software development company offering custom software, SaaS products, web development, mobile apps, and digital marketing services globally. 500+ projects delivered. Get free quote today!",
  keywords: [
    // Core Services
    "software development company",
    "best software development company",
    "software development agency",
    "custom software development",
    "software development services",
    "enterprise software development",
    "SaaS development company",
    "SaaS product development",
    "web development company",
    "best web development company",
    "web development agency",
    "custom web development",
    "website development services",
    "e-commerce website development",
    "mobile app development company",
    "mobile app development services",
    "iOS app development",
    "Android app development",
    "digital marketing company",
    "best digital marketing agency",
    "digital marketing services",
    "SEO services company",
    "SEO agency",
    "PPC advertising services",
    "social media marketing agency",

    // India Locations
    "software development company India",
    "web development company India",
    "digital marketing company India",
    "mobile app development India",
    "software company Chennai",
    "software company Bangalore",
    "software company Hyderabad",
    "software company Mumbai",
    "software company Delhi",
    "software company Kerala",
    "software company Tamil Nadu",
    "software company Salem",
    "software company Coimbatore",
    "web development Chennai",
    "web development Bangalore",
    "web development Kochi",
    "web development Trivandrum",
    "digital marketing Chennai",
    "digital marketing Bangalore",
    "digital marketing Kerala",
    "digital marketing Salem",
    "SEO services Chennai",
    "SEO services Bangalore",
    "SEO services Kerala",

    // Global Countries
    "software development USA",
    "software development UK",
    "software development Canada",
    "software development Australia",
    "software development Germany",
    "software development France",
    "software development UAE",
    "software development Dubai",
    "software development Saudi Arabia",
    "software development Singapore",
    "software development Malaysia",
    "software development New York",
    "software development Los Angeles",
    "software development London",
    "software development Toronto",
    "software development Sydney",
    "software development Berlin",
    "software development Paris",
    "web development USA",
    "web development UK",
    "web development Dubai",
    "web development Singapore",
    "digital marketing USA",
    "digital marketing UK",
    "digital marketing Dubai",
    "digital marketing Singapore",
    "digital marketing Canada",
    "digital marketing Australia",

    // Target Audiences
    "startup software development",
    "startup web development",
    "startup digital marketing",
    "enterprise software solutions",
    "business software development",
    "SMB software development",
    "small business website development",
    "restaurant website development",
    "hotel website development",
    "healthcare software development",
    "hospital management software",
    "clinic management software",
    "education software development",
    "real estate software development",
    "e-commerce software development",
    "finance software development",
    "logistics software development",
    "retail software development",
    "manufacturing software development",

    // Product Keywords
    "The Doctor Pro",
    "doctor management software",
    "clinic management system",
    "patient management system",
    "hospital management software",
    "medical software India",

    // Service Specific
    "React development services",
    "Node.js development services",
    "Python development services",
    "PHP web development",
    "Angular development",
    "Vue.js development",
    "full stack development",
    "front end development",
    "back end development",
    "API development services",
    "cloud computing services",
    "AWS development",
    "Azure development",
    "Google Cloud development",
    "database development",
    "UI UX design services",
    "graphic design services",
    "logo design company",
    "brand identity services",

    // Marketing Specific
    "content marketing services",
    "email marketing services",
    "influencer marketing",
    "video marketing services",
    "local SEO services",
    "e-commerce SEO",
    "Google Ads management",
    "Facebook Ads agency",
    "Instagram marketing",
    "LinkedIn marketing",
    "YouTube marketing",
    "online reputation management",
    "conversion rate optimization",
    "lead generation services",

    // Industry Terms
    "AI development company",
    "machine learning development",
    "blockchain development",
    "IoT development",
    "data analytics company",
    "cloud migration services",
    "Cybersecurity company",
    "IT consulting services",
    "IT support services",
    "website maintenance services",

    // India States
    "software development Tamil Nadu",
    "software development Kerala",
    "software development Karnataka",
    "software development Maharashtra",
    "software development Gujarat",
    "software development Delhi",
    "software development Andhra Pradesh",
    "software development Telangana",
    "software development West Bengal",
    "software development Punjab",
    "software development Rajasthan",
    "software development Madhya Pradesh",
    "software development Uttar Pradesh",
    "software development Bihar",
    "software development Odisha",
    "software development Haryana",
    "software development Assam",
    "software development Jharkhand",
    "software development Chhattisgarh",
    "software development Uttarakhand",
    "software development Goa",

    // India Cities
    "software development Chennai",
    "software development Bangalore",
    "software development Hyderabad",
    "software development Mumbai",
    "software development Delhi",
    "software development Pune",
    "software development Kolkata",
    "software development Ahmedabad",
    "software development Jaipur",
    "software development Lucknow",
    "software development Kochi",
    "software development Trivandrum",
    "software development Coimbatore",
    "software development Madurai",
    "software development Tiruchirappalli",
    "software development Salem",
    "software development Vellore",
    "software development Erode",
    "software development Tirunelveli",
    "software development Thanjavur",
    "web development Chennai",
    "web development Bangalore",
    "web development Hyderabad",
    "web development Mumbai",
    "web development Delhi",
    "web development Pune",
    "web development Kochi",
    "web development Coimbatore",
    "web development Salem",
    "web development Kerala",

    // More Global Cities
    "software development New York",
    "software development Los Angeles",
    "software development Chicago",
    "software development San Francisco",
    "software development Seattle",
    "software development Boston",
    "software development Austin",
    "software development Denver",
    "software development London",
    "software development Manchester",
    "software development Birmingham",
    "software development Edinburgh",
    "software development Toronto",
    "software development Vancouver",
    "software development Montreal",
    "software development Sydney",
    "software development Melbourne",
    "software development Brisbane",
    "software development Perth",
    "software development Auckland",
    "software development Berlin",
    "software development Munich",
    "software development Frankfurt",
    "software development Hamburg",
    "software development Paris",
    "software development Lyon",
    "software development Marseille",
    "software development Amsterdam",
    "software development Brussels",
    "software development Zurich",
    "software development Vienna",
    "software development Stockholm",
    "software development Copenhagen",
    "software development Oslo",
    "software development Helsinki",
    "software development Dubai",
    "software development Abu Dhabi",
    "software development Doha",
    "software development Riyadh",
    "software development Jeddah",
    "software development Muscat",
    "software development Kuwait",
    "software development Bahrain",
    "software development Singapore",
    "software development Kuala Lumpur",
    "software development Jakarta",
    "software development Manila",
    "software development Bangkok",
    "software development Ho Chi Minh",
    "software development Hanoi",
    "software development Hong Kong",
    "software development Taiwan",
    "software development Seoul",
    "software development Tokyo",
    "software development Osaka",

    // More Countries
    "software development Brazil",
    "software development Mexico",
    "software development Argentina",
    "software development Chile",
    "software development Colombia",
    "software development Peru",
    "software development South Africa",
    "software development Nigeria",
    "software development Kenya",
    "software development Egypt",
    "software development Morocco",
    "software development Turkey",
    "software development Russia",
    "software development Poland",
    "software development Czech Republic",
    "software development Hungary",
    "software development Romania",
    "software development Ukraine",
    "software development Greece",
    "software development Portugal",
    "software development Spain",
    "software development Ireland",
    "software development Scotland",
    "software development Wales",
    "software development Northern Ireland",
    "software development Israel",
    "software development Pakistan",
    "software development Bangladesh",
    "software development Sri Lanka",
    "software development Nepal",
    "software development Myanmar",
    "software development Vietnam",
    "software development Cambodia",
    "software development Laos",
    "software development Indonesia",
    "software development Philippines",
    "software development New Zealand",
    "software development Canada",

    // Long-tail Keywords
    "hire software developers",
    "hire web developers",
    "hire mobile app developers",
    "hire digital marketers",
    "best software company near me",
    "near me software development",
    "affordable software development",
    "professional web development",
    "custom website design",
    "best SEO company",
    "top digital marketing agency",
    "software development cost",
    "website development cost",
    "mobile app development cost",
    "digital marketing pricing",
    "software development process",
    "agile software development",
    "offshore software development",
    "dedicated development team",
    "software outsourcing company",

    // Business Types
    "startup software solutions",
    "enterprise software provider",
    "business automation software",
    "digital transformation company",
    "technology consulting firm",
    "IT solutions provider",
    "custom software vendor",
    "software development partner",

    // Technical Skills
    "Java development",
    "Python development",
    "JavaScript development",
    "TypeScript development",
    ".NET development",
    "Ruby development",
    "Go development",
    "Rust development",
    "Swift development",
    "Kotlin development",
    "Flutter development",
    "React Native development",
    "Django development",
    "Laravel development",
    "WordPress development",
    "Shopify development",
    "WooCommerce development",
    "Magento development",

    // Local Business Keywords
    "IT company near me",
    "software agency near me",
    "web design company near me",
    "digital agency near me",
    "SEO company near me",
    "marketing agency near me",
    "app development company near me",
    "local software company",
    "local web developer",
    "near me web development",
    "near me digital marketing",

    // Salem Specific (Primary Market)
    "software development Salem",
    "web development Salem",
    "digital marketing Salem",
    "SEO services Salem",
    "website development Salem",
    "mobile app development Salem",
    "IT company Salem",
    "software company Salem",
    "web design Salem",
    "digital agency Salem",
    "SEO company Salem",
    "marketing agency Salem",
    "app developer Salem",
    "software developer Salem",
    "website designer Salem",
    "graphic design Salem",
    "logo design Salem",
    "branding services Salem",
    "content marketing Salem",
    "social media marketing Salem",
    "PPC agency Salem",
    "Google Ads Salem",
    "Facebook ads Salem",
    "local SEO Salem",
    "e-commerce website Salem",
    "business website Salem",
    "corporate website Salem",
    "portfolio website Salem",
    "startup website Salem",
    "restaurant website Salem",
    "hotel website Salem",
    "hospital software Salem",
    "clinic software Salem",
    "doctor software Salem",
    "education software Salem",
    "real estate software Salem",
    "ecommerce software Salem",

    // Kerala Specific
    "software development Kerala",
    "web development Kerala",
    "digital marketing Kerala",
    "SEO services Kerala",
    "website development Kerala",
    "IT company Kerala",
    "software company Kerala",
    "web design Kerala",
    "digital agency Kerala",
    "SEO company Kerala",
    "mobile app development Kerala",
    "app developer Kerala",
    "software developer Kerala",
    "website designer Kerala",
    "logo design Kerala",
    "hospital management software Kerala",
    "clinic software Kerala",
    "doctor software Kerala",

    // UAE/Dubai Specific
    "software development Dubai",
    "web development Dubai",
    "digital marketing Dubai",
    "SEO services Dubai",
    "website development Dubai",
    "IT company Dubai",
    "software company Dubai",
    "web design Dubai",
    "digital agency Dubai",
    "SEO company Dubai",
    "marketing agency Dubai",
    "mobile app development Dubai",
    "app developer Dubai",
    "startup Dubai",
    "business setup Dubai",

    // USA Cities
    "software development New York City",
    "software development Los Angeles",
    "software development Chicago",
    "software development Houston",
    "software development Phoenix",
    "software development Philadelphia",
    "software development San Antonio",
    "software development San Diego",
    "software development Dallas",
    "software development San Jose",
    "software development Austin",
    "software development Jacksonville",
    "software development Fort Worth",
    "software development Columbus",
    "software development Charlotte",
    "software development Indianapolis",
    "software development Seattle",
    "software development Denver",
    "software development Boston",
    "software development Detroit",
    "software development Nashville",
    "software development Portland",
    "software development Las Vegas",
    "software development Memphis",
    "software development Louisville",
    "software development Baltimore",
    "software development Milwaukee",
    "software development Albuquerque",
    "software development Tucson",
    "software development Fresno",
    "software development Sacramento",
    "software development Kansas City",
    "software development Atlanta",
    "software development Miami",
    "software development Cleveland",
    "software development Omaha",

    // UK Cities
    "software development London",
    "software development Birmingham",
    "software development Manchester",
    "software development Glasgow",
    "software development Liverpool",
    "software development Bristol",
    "software development Sheffield",
    "software development Leeds",
    "software development Edinburgh",
    "software development Leicester",
    "software development Bradford",
    "software development Cardiff",
    "software development Coventry",
    "software development Belfast",
    "software development Nottingham",
    "software development Kingston upon Hull",
    "software development Newcastle",
    "software development Derby",
    "software development Portsmouth",
    "software development Southampton",
    "software development Wolverhampton",
    "software development Plymouth",
    "software development Westminster",

    // Australia Cities
    "software development Sydney",
    "software development Melbourne",
    "software development Brisbane",
    "software development Perth",
    "software development Adelaide",
    "software development Canberra",
    "software development Gold Coast",
    "software development Newcastle",
    "software development Wollongong",
    "software development Geelong",
    "software development Darwin",

    // Canada Cities
    "software development Toronto",
    "software development Montreal",
    "software development Calgary",
    "software development Ottawa",
    "software development Edmonton",
    "software development Mississauga",
    "software development Winnipeg",
    "software development Vancouver",
    "software development Quebec City",
    "software development Hamilton",

    // Germany Cities
    "software development Berlin",
    "software development Hamburg",
    "software development Munich",
    "software development Cologne",
    "software development Frankfurt",
    "software development Stuttgart",
    "software development Düsseldorf",
    "software development Leipzig",
    "software development Dortmund",
    "software development Essen",
    "software development Dresden",

    // France Cities
    "software development Paris",
    "software development Marseille",
    "software development Lyon",
    "software development Toulouse",
    "software development Nice",
    "software development Nantes",
    "software development Montpellier",
    "software development Strasbourg",
    "software development Bordeaux",
    "software development Lille",

    // Singapore
    "software development Singapore",
    "web development Singapore",
    "digital marketing Singapore",
    "SEO services Singapore",
    "mobile app development Singapore",
    "IT company Singapore",

    // Malaysia
    "software development Kuala Lumpur",
    "web development Kuala Lumpur",
    "digital marketing Malaysia",

    // Saudi Arabia
    "software development Riyadh",
    "software development Jeddah",
    "software development Dammam",

    // Qatar
    "software development Doha",

    // Search Intent Keywords
    "how to hire software developer",
    "cost of website development",
    "best web development framework",
    "how to build a SaaS product",
    "steps to create mobile app",
    "digital marketing strategy for small business",
    "how to improve SEO ranking",
    "benefits of custom software",
    "why choose React for web development",
    "importance of UI UX design",

    // Comparison Keywords
    "React vs Angular vs Vue",
    "Node.js vs Python",
    "iOS vs Android development",
    "custom vs template website",
    "SEO vs PPC",
    "freelancer vs agency",
    "nearshore vs offshore development",

    // Problem/Solution Keywords
    "fix slow website",
    "improve website traffic",
    "generate more leads",
    "build mobile app startup",
    "digital transformation guide",
    "choose right software company",
    "website security best practices",
    "mobile app marketing strategy",

    // Target Audience - Industry
    "healthcare software solutions",
    "fintech software development",
    "edtech software company",
    "real estate software provider",
    "ecommerce software development",
    "logistics software company",
    "manufacturing software solutions",
    "retail software development",
    "hospitality software",
    "construction software development",

    // Target Audience - Company Size
    "startup MVP development",
    "small business software",
    "mid-market enterprise software",
    "large corporation IT solutions",
    "SMB digital transformation",

    // Target Audience - Role
    "CTO software development",
    "CEO digital marketing",
    "CFO software budget",
    "startup founder development",
    "marketing director SEO",
    "IT manager software vendor",

    // Additional Services
    "blockchain development company",
    "AI machine learning development",
    "data science consulting",
    "IoT software development",
    "cloud computing services",
    "DevOps consulting",
    "cybersecurity services",
    "IT security company",
    "software testing services",
    "QA automation services",

    // Content Types
    "blog website development",
    "news portal development",
    "directory website",
    "job portal development",
    "social network development",
    "marketplace development",
    "booking system development",
    "CRM development",
    "ERP system development",
    "accounting software development",

    // Technology
    "React Next.js development",
    "Vue Nuxt development",
    "Angular development",
    "Node Express development",
    "Python Django development",
    "Laravel development",
    "WordPress development",
    "Shopify development",
    "WooCommerce development",
    "Magento development",

    // Design
    "UI UX design company",
    "graphic design services",
    "logo design agency",
    "brand identity design",
    "web design services",
    "mobile app design",
    "product design services",
    "prototype design",
    "wireframe design",
    "design thinking consulting",

    // Marketing Digital
    "SEO content marketing",
    "social media management",
    "PPC campaign management",
    "email marketing automation",
    "influencer marketing strategy",
    "video production services",
    "content strategy",
    "digital branding",
    "online marketing services",
    "growth hacking",

    // Old keywords preserved for continuity
    "digital marketing Dubai",
    "digital marketing Salem",
    "digital marketing Kerala",
  "best digital marketing agency UK",
  "software development USA",
  "website development company Kerala",
  "web development Tamil Nadu",
  "SEO services Dubai UAE",
  "social media marketing UK",
  "PPC advertising USA",
  "mobile app development India",
  "ecommerce website development USA",
  "AI marketing tools UK",
  "voice search optimization Dubai",
  "responsive web design Kerala",
  "website maintenance Tamil Nadu",
  "custom software solutions USA",
  "digital transformation services UK",
  "branding and UX design Dubai",
  "cloud software development India",
  "local SEO Tamil Nadu",
  "content marketing strategies USA",
  "online reputation management UK",
  "web hosting and domain Dubai",
  "enterprise software solutions USA",
  "UI/UX designer Kerala",
  "frontend and backend development Tamil Nadu",
  "website speed optimization UK",
  "cybersecurity software USA",
  "ai chatbot development Dubai",
    "digital marketing services in Salem", 
    "digital marketing agency Salem", 
    "Salem digital marketing company", 
    "digital marketing firm Salem", 
    "online marketing services in Salem", 
    "SEO services Salem", 
    "Salem social media marketing", 
    "PPC agency Salem", 
    "best digital marketing agency in Salem", 
    "local SEO Salem", 
    "Salem branding services", 
    "Salem digital advertising", 
    "creative agency Salem", 
    "visual search SEO Salem", 
    "Salem digital marketing expert", 
    "branding and marketing Salem", 
    "content marketing agency Salem", 
    "performance marketing Salem", 
    "digital marketing consultant Salem", 
    "Salem internet marketing", 
    "Google Ads agency Salem", 
    "social media agency Salem", 
    "digital marketing specialist Salem", 
    "digital marketing solutions Salem", 
    "Salem website marketing", 
    "digital marketing company near me", 
    "digital marketing services near me", 
    "online advertising Salem", 
    "digital marketing for local business Salem", 
    "lead generation Salem", 
    "AI digital marketing Salem", 
    "digital campaign Salem", 
    "internet marketing agency Salem", 
    "Salem online presence", 
    "digital brand management Salem", 
    "digital marketing for startups Salem", 
    "paid advertising Salem", 
    "Salem marketing services", 
    "best SEO company Salem", 
    "Salem digital transformation", 
    "digital marketing promotion Salem", 
    "Salem influencer marketing", 
    "ecommerce marketing Salem", 
    "Salem SEM services", 
    "Salem SMO agency", 
    "digital marketing packages Salem", 
    "hyperlocal digital marketing Salem", 
    "SEO expert Salem", 
    "digital marketing Salem Tamil Nadu",
    
    "web development salem",
"website development salem",
"web development company salem",
"website development company salem",
"web application development salem",
"web development services salem",
"frontend developer salem",
"backend developer salem",
"python web development salem",
"react development salem",
"node.js development salem",
"freelance web developer salem",
"ecommerce website development salem",
"web programming salem",
"web design and development salem",
"web dev salem",
"web development agency salem",
"website developer near me salem",
"web design near me salem",
"html5 development salem",
"css3 styling salem",
"database integration salem",
"custom web development salem",
"enterprise web solutions salem",
"web development packages salem",
"website pricing plans salem",
"web development firm salem",
"wordpress developer salem",
"local SEO web developer salem",
"best web development company salem",
"responsive web design salem",
"mobile web development salem",
"technology stack development salem",
"net developer salem",
"angular developer salem",
"vue.js developer salem",
"full stack developer salem",
"website redesign salem",
"maintenance web development salem",
"online presence salem",
"SEO for website salem",
"website optimization salem",
"custom ecommerce development salem",
"business website salem",
"industry web development salem",
"travel agency web development salem",
"construction company website salem",
"manufacturing company website salem",
"healthcare website development salem",
"educational website development salem",
"real estate web development salem",
"salem web consultant",
"web hosting services salem",
"domain registration salem",
"UI/UX design salem",
"mobile responsive website salem",
"cms website solutions salem",
"custom cms development salem",
"dynamic website development salem",
"static website development salem",
"React JS development salem",
"Node JS integration salem",
"API integration development salem",
"social media integration website salem",
"SEO expert salem",
"website marketing salem",
"digital marketing web development salem",
"Portfolio website development salem",
"product website development salem",
"B2B web development salem",
"B2C web development salem",
"salem landing page design",
"corporate profile website salem",
"company presentations website salem",
"web server hosting salem",
"SSL certificate setup salem",
"secure website development salem",
"web analytics salem",
"keywords ranking website salem",
"Google business profile optimization salem",
"local business website salem",
"bespoke website development salem",
"custom plugins development salem",
"WordPress optimization salem",
"MERN stack web development salem",
"UI frameworks salem",
"Bootstrap website salem",
"website content development salem",
"industry-specific web development salem",
"online booking website salem",
"appointment scheduling web development salem",
"shopify web development salem",
"Magento website development salem",
"WooCommerce website development salem",
"web portal development salem",
"progressive web app development salem",
"cloud hosting website salem",
"website support services salem",
"SEO audit website salem",
"site performance optimization salem",
"cross-platform web development salem",
"multilingual website development salem",
"custom dashboards website salem",
"web design for SMEs salem",
"web development salem",
"website development salem",
"web development company salem",
"website development company salem",
"web application development salem",
"web development services salem",
"frontend developer salem",
"backend developer salem",
"python web development salem",
"react development salem",
"node.js development salem",
"freelance web developer salem",
"ecommerce website development salem",
"web programming salem",
"web design and development salem",
"web dev salem",
"web development agency salem",
"website developer near me salem",
"web design near me salem",
"html5 development salem",
"css3 styling salem",
"database integration salem",
"custom web development salem",
"enterprise web solutions salem",
"web development packages salem",
"website pricing plans salem",
"web development firm salem",
"wordpress developer salem",
"local SEO web developer salem",
"best web development company salem",
"responsive web design salem",
"mobile web development salem",
"technology stack development salem",
"net developer salem",
"angular developer salem",
"vue.js developer salem",
"full stack developer salem",
"website redesign salem",
"maintenance web development salem",
"online presence salem",
"SEO for website salem",
"website optimization salem",
"custom ecommerce development salem",
"business website salem",
"industry web development salem",
"travel agency web development salem",
"construction company website salem",
"manufacturing company website salem",
"healthcare website development salem",
"educational website development salem",
"real estate web development salem",
"salem web consultant",
"web hosting services salem",
"domain registration salem",
"UI/UX design salem",
"mobile responsive website salem",
"cms website solutions salem",
"custom cms development salem",
"dynamic website development salem",
"static website development salem",
"React JS development salem",
"Node JS integration salem",
"API integration development salem",
"social media integration website salem",
"SEO expert salem",
"website marketing salem",
"digital marketing web development salem",
"Portfolio website development salem",
"product website development salem",
"B2B web development salem",
"B2C web development salem",
"salem landing page design",
"corporate profile website salem",
"company presentations website salem",
"web server hosting salem",
"SSL certificate setup salem",
"secure website development salem",
"web analytics salem",
"keywords ranking website salem",
"Google business profile optimization salem",
"local business website salem",
"bespoke website development salem",
"custom plugins development salem",
"WordPress optimization salem",
"MERN stack web development salem",
"UI frameworks salem",
"Bootstrap website salem",
"website content development salem",
"industry-specific web development salem",
"online booking website salem",
"appointment scheduling web development salem",
"shopify web development salem",
"Magento website development salem",
"WooCommerce website development salem",
"web portal development salem",
"progressive web app development salem",
"cloud hosting website salem",
"website support services salem",
"SEO audit website salem",
"site performance optimization salem",
"cross-platform web development salem",
"multilingual website development salem",
"custom dashboards website salem",
"web design for SMEs salem",
  "Digital Marketing near me Dubai",
  "Digital Marketing Dubai near me",
  "best Digital Marketing Dubai",
  "Digital Marketing best Dubai",
  "top Digital Marketing Dubai",
  "Digital Marketing top Dubai",
  "affordable Digital Marketing Dubai",
  "Digital Marketing affordable Dubai",
  "Digital Marketing packages Dubai",
  "Digital Marketing Dubai packages",
  "Digital Marketing agency Dubai",
  "Digital Marketing Dubai agency",
  "Digital Marketing company Dubai",
  "Digital Marketing Dubai company",
  "Digital Marketing services Dubai",
  "Digital Marketing Dubai services",
  "Digital Marketing expert Dubai",
  "Digital Marketing Dubai expert",
  "Digital Marketing consultant Dubai",
  "Digital Marketing Dubai consultant",
  "Digital Marketing solutions Dubai",
  "Digital Marketing Dubai solutions",

  // Software
  "Software near me Dubai",
  "Software Dubai near me",
  "best Software Dubai",
  "Software best Dubai",
  "top Software Dubai",
  "Software top Dubai",
  "affordable Software Dubai",
  "Software affordable Dubai",
  "Software packages Dubai",
  "Software Dubai packages",
  "Software agency Dubai",
  "Software Dubai agency",
  "Software company Dubai",
  "Software Dubai company",
  "Software services Dubai",
  "Software Dubai services",
  "Software expert Dubai",
  "Software Dubai expert",
  "Software consultant Dubai",
  "Software Dubai consultant",
  "Software solutions Dubai",
  "Software Dubai solutions",

  // Website
  "Website near me Dubai",
  "Website Dubai near me",
  "best Website Dubai",
  "Website best Dubai",
  "top Website Dubai",
  "Website top Dubai",
  "affordable Website Dubai",
  "Website affordable Dubai",
  "Website packages Dubai",
  "Website Dubai packages",
  "Website agency Dubai",
  "Website Dubai agency",
  "Website company Dubai",
  "Website Dubai company",
  "Website services Dubai",
  "Website Dubai services",
  "Website expert Dubai",
  "Website Dubai expert",
  "Website consultant Dubai",
  "Website Dubai consultant",
  "Website solutions Dubai",
  "Website Dubai solutions",

  // --- Salem variations ---
  // Digital Marketing
  "Digital Marketing near me Salem",
  "Digital Marketing Salem near me",
  "best Digital Marketing Salem",
  "Digital Marketing best Salem",
  "top Digital Marketing Salem",
  "Digital Marketing top Salem",
  "affordable Digital Marketing Salem",
  "Digital Marketing affordable Salem",
  "Digital Marketing packages Salem",
  "Digital Marketing Salem packages",
  "Digital Marketing agency Salem",
  "Digital Marketing Salem agency",
  "Digital Marketing company Salem",
  "Digital Marketing Salem company",
  "Digital Marketing services Salem",
  "Digital Marketing Salem services",
  "Digital Marketing expert Salem",
  "Digital Marketing Salem expert",
  "Digital Marketing consultant Salem",
  "Digital Marketing Salem consultant",
  "Digital Marketing solutions Salem",
  "Digital Marketing Salem solutions",

  // Software
  "Software near me Salem",
  "Software Salem near me",
  "best Software Salem",
  "Software best Salem",
  "top Software Salem",
  "Software top Salem",
  "affordable Software Salem",
  "Software affordable Salem",
  "Software packages Salem",
  "Software Salem packages",
  "Software agency Salem",
  "Software Salem agency",
  "Software company Salem",
  "Software Salem company",
  "Software services Salem",
  "Software Salem services",
  "Software expert Salem",
  "Software Salem expert",
  "Software consultant Salem",
  "Software Salem consultant",
  "Software solutions Salem",
  "Software Salem solutions",

  // Website
  "Website near me Salem",
  "Website Salem near me",
  "best Website Salem",
  "Website best Salem",
  "top Website Salem",
  "Website top Salem",
  "affordable Website Salem",
  "Website affordable Salem",
  "Website packages Salem",
  "Website Salem packages",
  "Website agency Salem",
  "Website Salem agency",
  "Website company Salem",
  "Website Salem company",
  "Website services Salem",
  "Website Salem services",
  "Website expert Salem",
  "Website Salem expert",
  "Website consultant Salem",
  "Website Salem consultant",
  "Website solutions Salem",
  "Website Salem solutions",

  // --- Kerala variations ---
  // Digital Marketing
  "Digital Marketing near me Kerala",
  "Digital Marketing Kerala near me",
  "best Digital Marketing Kerala",
  "Digital Marketing best Kerala",
  "top Digital Marketing Kerala",
  "Digital Marketing top Kerala",
  "affordable Digital Marketing Kerala",
  "Digital Marketing affordable Kerala",
  "Digital Marketing packages Kerala",
  "Digital Marketing Kerala packages",
  "Digital Marketing agency Kerala",
  "Digital Marketing Kerala agency",
  "Digital Marketing company Kerala",
  "Digital Marketing Kerala company",
  "Digital Marketing services Kerala",
  "Digital Marketing Kerala services",
  "Digital Marketing expert Kerala",
  "Digital Marketing Kerala expert",
  "Digital Marketing consultant Kerala",
  "Digital Marketing Kerala consultant",
  "Digital Marketing solutions Kerala",
  "Digital Marketing Kerala solutions",

  // Software
  "Software near me Kerala",
  "Software Kerala near me",
  "best Software Kerala",
  "Software best Kerala",
  "top Software Kerala",
  "Software top Kerala",
  "affordable Software Kerala",
  "Software affordable Kerala",
  "Software packages Kerala",
  "Software Kerala packages",
  "Software agency Kerala",
  "Software Kerala agency",
  "Software company Kerala",
  "Software Kerala company",
  "Software services Kerala",
  "Software Kerala services",
  "Software expert Kerala",
  "Software Kerala expert",
  "Software consultant Kerala",
  "Software Kerala consultant",
  "Software solutions Kerala",
  "Software Kerala solutions",

  // Website
  "Website near me Kerala",
  "Website Kerala near me",
  "best Website Kerala",
  "Website best Kerala",
  "top Website Kerala",
  "Website top Kerala",
  "affordable Website Kerala",
  "Website affordable Kerala",
  "Website packages Kerala",
  "Website Kerala packages",
  "Website agency Kerala",
  "Website Kerala agency",
  "Website company Kerala",
  "Website Kerala company",
  "Website services Kerala",
  "Website Kerala services",
  "Website expert Kerala",
  "Website Kerala expert",
  "Website consultant Kerala",
  "Website Kerala consultant",
  "Website solutions Kerala",
  "Website Kerala solutions",
  "website development company in Salem",
  "best website development company Salem",
  "top web design company Salem",
  "affordable web design Salem",
  "professional website design Salem",
  "ecommerce website development Salem",
  "custom website design Salem",
  "WordPress website development Salem",
  "business website design Salem",
  "corporate website design Salem",
  "website redesign services Salem",
  "responsive website design Salem",
  "static website development Salem",
  "dynamic website development Salem",
  "small business website design Salem",
  "web hosting services Salem",
  "domain registration Salem",
  "SEO friendly website design Salem",
  "UI UX design company Salem",
  "mobile friendly website design Salem",
  "digital marketing agency in Salem",
  "best digital marketing company Salem",
  "top digital marketing services Salem",
  "affordable digital marketing Salem",
  "SEO services in Salem",
  "local SEO services Salem",
  "search engine optimization Salem",
  "SEO expert in Salem",
  "PPC advertising company Salem",
  "Google Ads service Salem",
  "Facebook ads expert Salem",
  "Instagram marketing agency Salem",
  "YouTube marketing services Salem",
  "social media marketing agency Salem",
  "SMM company in Salem",
  "content marketing agency Salem",
  "email marketing services Salem",
  "digital branding company Salem",
  "branding and digital marketing Salem",
  "online marketing services Salem",
  "digital strategy consulting Salem",
  "digital marketing consultant Salem",
  "digital transformation services Salem",
  "online reputation management Salem",
  "ORM services Salem",
  "performance marketing agency Salem",
  "lead generation services Salem",
  "affiliate marketing services Salem",
  "growth marketing company Salem",
  "startup digital marketing Salem",
  "digital marketing for businesses Salem",
  "digital advertising company Salem",
  "digital promotions Salem",
  "ecommerce SEO services Salem",
  "ecommerce marketing company Salem",
  "Google my business optimization Salem",
  "local business online marketing Salem",
  "IT company in Salem",
  "top IT solutions Salem",
  "software development company Salem",
  "mobile app development company Salem",
  "Android app development Salem",
  "iOS app development Salem",
  "custom app development Salem",
  "hybrid app development Salem",
  "web application development Salem",
  "CRM software development Salem",
  "ERP software solutions Salem",
  "custom software development Salem",
  "IT consulting company Salem",
  "graphic design services Salem",
  "creative design company Salem",
  "logo design company Salem",
  "branding services Salem",
  "brochure design Salem",
  "flyer design company Salem",
  "digital creatives company Salem",
  "UI UX design services Salem",
  "video marketing services Salem",
  "motion graphics company Salem",
  "animation services Salem",
  "explainer video services Salem",
  "corporate video production Salem",
  "website maintenance company Salem",
  "IT support services Salem",
  "cloud hosting services Salem",
  "cybersecurity company Salem",
  "data analytics company Salem",
  "AI solutions company Salem",
  "marketing automation services Salem",
  "conversion rate optimization Salem",
  "sales funnel marketing Salem",
  "local business SEO Salem",
  "digital marketing near me Salem",
  "website design near me Salem",
  "IT services near me Salem",
  "best web developers in Salem",
  "top digital marketers Salem",
  "website company near me Salem",
  "SEO company near me Salem",
    
  "website development Kerala",
 "website designers Kerala",
 "website design company Kerala",
 "website services Kerala",
 "web development Kerala",
 "web design Kerala",
 "web development company Kerala",
 "custom website development Kerala",
 "business website Kerala",
 "ecommerce website Kerala",
 "professional website Kerala",
 "corporate website Kerala",
 "responsive web design Kerala",
 "dynamic website Kerala",
 "static website Kerala",
 "cheap website Kerala",
 "affordable website Kerala",
 "top website designers Kerala",
 "best website company Kerala",
 "freelance web designer Kerala",
 "startup website Kerala",
 "portfolio website Kerala",
 "landing page design Kerala",
 "wordpress website Kerala",
 "shopify website Kerala",
 "magento website Kerala",
 "joomla website Kerala",
 "cms website Kerala",
 "travel website Kerala",
 "hotel website Kerala",
 "restaurant website Kerala",
 "real estate website Kerala",
 "school website Kerala",
 "college website Kerala",
 "university website Kerala",
 "church website Kerala",
 "hospital website Kerala",
 "clinic website Kerala",
 "doctor website Kerala",
 "law firm website Kerala",
 "NGO website Kerala",
 "government website Kerala",
 "personal website Kerala",
 "blog website Kerala",
 "news portal Kerala",
 "classified website Kerala",
 "job portal Kerala",
 "directory website Kerala",
 "auction website Kerala",
 "booking website Kerala",
 "custom web portal Kerala",
 "web app Kerala",
 "progressive web app Kerala",
 "app integration Kerala",
 "mobile friendly website Kerala",
 "modern website design Kerala",
 "minimal website Kerala",
 "SEO friendly website Kerala",
 "software company Kerala",
 "software development Kerala",
 "custom software Kerala",
 "software development company Kerala",
 "software solutions Kerala",
 "business software Kerala",
 "ERP software Kerala",
 "CRM software Kerala",
 "accounting software Kerala",
 "hospital software Kerala",
 "school management software Kerala",
 "HR software Kerala",
 "POS software Kerala",
 "billing software Kerala",
 "inventory software Kerala",
 "cloud software Kerala",
 "retail software Kerala",
 "pharma software Kerala",
 "logistics software Kerala",
 "manufacturing software Kerala",
 "project management software Kerala",
 "AI software Kerala",
 "machine learning software Kerala",
 "automation software Kerala",
 "mobile app development Kerala",
 "android app development Kerala",
 "iOS app development Kerala",
 "app development Kerala",
 "cross platform apps Kerala",
 "hybrid app development Kerala",
 "flutter app development Kerala",
 "react native apps Kerala",
 "native apps Kerala",
 "UI UX design Kerala",
 "user interface design Kerala",
 "user experience Kerala",
 "prototyping Kerala",
 "wireframing Kerala",
 "product design Kerala",
 "digital marketing Kerala",
 "SEO services Kerala",
 "local SEO Kerala",
 "social media marketing Kerala",
 "branding services Kerala",
 "online marketing Kerala",
 "search engine optimization Kerala",
 "Google ads Kerala",
 "PPC services Kerala",
 "content marketing Kerala",
 "email marketing Kerala",
 "facebook ads Kerala",
 "instagram marketing Kerala",
 "linkedin marketing Kerala",
 "twitter marketing Kerala",
 "youtube marketing Kerala",
 "influencer marketing Kerala",
 "digital branding Kerala",
 "ORM services Kerala",
 "reputation management Kerala",
 "video marketing Kerala",
 "ecommerce marketing Kerala",
 "affiliate marketing Kerala",
 "digital strategy Kerala",
 "IT company Kerala",
 "IT services Kerala",
 "IT solutions Kerala",
 "IT consultancy Kerala",
 "IT outsourcing Kerala",
 "IT support Kerala",
 "IT infrastructure Kerala",
 "cloud services Kerala",
 "server management Kerala",
 "network solutions Kerala",
 "data security Kerala",
 "cybersecurity Kerala",
 "blockchain development Kerala",
 "AI development Kerala",
 "ML development Kerala",
 "data science Kerala",
 "big data solutions Kerala",
 "IoT solutions Kerala",
 "SaaS development Kerala",
 "PaaS services Kerala",
 "IT automation Kerala",
 "software testing Kerala",
 "QA services Kerala",
 "devops Kerala",
 "system integration Kerala",
 "BNI Kerala",
 "BNI business networking Kerala",
 "BNI software Kerala",
 "BNI website Kerala",
 "BNI IT company Kerala",
 "BNI networking Kerala",
 "BNI members Kerala",
 "BNI entrepreneurs Kerala",
 "BNI business growth Kerala",
 "BNI chapter Kerala",
 "BNI meetings Kerala",
 "BNI events Kerala",
 "BNI startup Kerala",
 "BNI business Kerala",
 "BNI Kerala IT services",
 "BNI Kerala software solutions",
 "BNI Kerala website development",
 "BNI Kerala networking platform",
 "BNI company growth Kerala",
 "BNI entrepreneurs network Kerala",
 "BNI business referrals Kerala",
 "BNI corporate connections Kerala",
 "BNI digital Kerala",
 "BNI IT Kerala",
 "BNI technology Kerala",
 "BNI partnership Kerala",
 "BNI collaboration Kerala",
 "BNI startup ecosystem Kerala",
 "BNI software development Kerala",
 "BNI marketing Kerala",
 "BNI business circle Kerala",
 "BNI chapter meetings Kerala",
 "BNI events 2025 Kerala",
 "BNI Trivandrum Kerala",
 "BNI Kochi Kerala",
 "BNI Calicut Kerala",
 "BNI networking hub Kerala",
 "BNI entrepreneurs Kerala",
 "BNI global Kerala",
 "BNI innovation Kerala",
 "BNI digital solutions Kerala",
 "BNI Kerala technology solutions",
 "BNI Kerala IT consultancy",
 "BNI Kerala startup network",
 "BNI Kerala professionals",
 "BNI Kerala entrepreneurs club",
 "BNI Kerala business community",
 "BNI Kerala growth opportunities",
 "BNI Kerala collaborations",
 "BNI Kerala events",
 "BNI Kerala IT startups",
 "BNI Kerala software industry",
 "BNI Kerala business referrals",

  // perplexity
  "web development Kerala", "website development Kerala", "web design Kerala", "web developer Kerala", "ecommerce website development Kerala", "responsive website design Kerala", "web application development Kerala", "custom web development Kerala", "WordPress website development Kerala", "UI/UX design Kerala", "website developer in Kerala", "web development services Kerala", "web design company Kerala", "website designing company Kerala", "top web developer Kerala", "local website developer Kerala", "SEO company Kerala", "digital marketing Kerala", "freelance web designer Kerala", "best e-commerce website Kerala", "mobile website development Kerala", "CMS website development Kerala", "small business web development Kerala", "corporate website design Kerala", "custom theme integration Kerala", "web server hosting Kerala", "domain registration Kerala", "web page development Kerala", "landing page design Kerala", "hire web developer Kerala", "professional web developer Kerala", "top rated web development Kerala", "affordable website development Kerala", "startup website development Kerala", "portfolio website design Kerala", "kerala web developer agency", "web development support Kerala", "website redesign Kerala", "online business website Kerala", "ecommerce platform development Kerala", "custom website solutions Kerala", "web design expert Kerala", "web consulting Kerala", "website maintenance Kerala", "secure website design Kerala", "modern website development Kerala", "web design and development Kerala", "website optimization Kerala", "UI designer Kerala", "backend developer Kerala", "frontend developer Kerala", "JavaScript developer Kerala", "Python web development Kerala", "ReactJS developer Kerala", "Node.js development Kerala", "PHP web development Kerala", "Drupal website development Kerala", "Magento developer Kerala", "Shopify website development Kerala", "Woocommerce website development Kerala", "kerala website developers", "kerala web agency", "kerala web services", "high performance web design Kerala", "web development consultant Kerala", "site audit services Kerala", "local SEO expert Kerala", "kerala website content services", "web hosting services Kerala", "website management services Kerala", "website analytics Kerala", "local business web design Kerala", "sector-specific web development Kerala", "education institute website Kerala", "NGO website developer Kerala", "hospital website developer Kerala", "restaurant website development Kerala", "hotel website development Kerala", "real estate website development Kerala", "event website design Kerala", "school website developer Kerala", "news portal development Kerala", "travel website Kerala", "rentals website design Kerala", "job portal website Kerala", "online booking development Kerala", "creative web design Kerala", "interactive website Kerala", "business website design Kerala", "lead generation website Kerala", "conversion website design Kerala", "mini site development Kerala", "fast loading website Kerala", "SEO friendly website Kerala", "brand website development Kerala", "company website developer Kerala", "personal website designer Kerala", "online catalog website Kerala", "customer-centric web developer Kerala", "B2B website development Kerala", "B2C web design Kerala", "mobile app developer Kerala", "web app developer Kerala", "API integration website Kerala", "custom plugin developer Kerala", "web security solutions Kerala",

  ],
  openGraph: {
    title: "MyEnum Agency | Best Software Development Company India & Global",
    description:
      "Top-rated software development company offering custom software, SaaS products, web development, mobile apps, and digital marketing services globally. 500+ projects delivered.",
    url: "https://www.myenum.in",
    siteName: "MyEnum Agency",
    images: [
      {
        url: "https://www.myenum.in/og-image.png",
        width: 1200,
        height: 630,
        alt: "MyEnum Agency - Software Development & Digital Marketing",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MyEnum Agency | Best Software Development Company India & Global",
    description:
      "Top-rated software development company offering custom software, SaaS products, web development, mobile apps, and digital marketing services globally.",
    images: ["https://www.myenum.in/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const schemaData = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "MyEnum Agency",
    "alternateName": "MyEnum Digital Agency",
    "url": "https://www.myenum.in",
    "logo": "https://www.myenum.in/logo.png",
    "description": "Premium software development and digital marketing agency in India. Specializing in custom software, SaaS products, web development, and digital marketing services.",
    "foundingDate": "2020",
    "numberOfEmployees": {
      "@type": "QuantitativeValue",
      "minValue": 10,
      "maxValue": 50
    },
    "address": {
      "@type": "PostalAddress",
      "addressCountry": "IN",
      "addressRegion": "Tamil Nadu",
      "addressLocality": "Salem"
    },
    "contactPoint": {
      "@type": "ContactPoint",
      "contactType": "customer service",
      "availableLanguage": ["English", "Tamil", "Hindi"]
    },
    "sameAs": [
      "https://www.facebook.com/myenum",
      "https://www.linkedin.com/company/myenum",
      "https://www.instagram.com/myenum",
      "https://twitter.com/myenum"
    ],
    "areaServed": [
      {
        "@type": "Country",
        "name": "India"
      },
      {
        "@type": "Country",
        "name": "United Arab Emirates"
      },
      {
        "@type": "Country",
        "name": "United States"
      },
      {
        "@type": "Country",
        "name": "United Kingdom"
      }
    ],
    "serviceType": [
      "Software Development",
      "Web Development",
      "Mobile App Development",
      "Digital Marketing",
      "SaaS Development",
      "E-commerce Solutions"
    ]
  };

  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} antialiased dark text-slate-50`}
    >
      <body>
        <ClientLayout>{children}</ClientLayout>

        {/* Schema.org JSON-LD */}
        <Script
          id="schema-org"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
        />

        {/* Microsoft Clarity */}
        <Script id="clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "svumhdjdy5");
          `}
        </Script>

        {/* Ahrefs Analytics */}
        <script
          src="https://analytics.ahrefs.com/analytics.js"
          data-key="K/mXjnOi6MxGC51EZCroJg"
          async
        ></script>

        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-DE486L9YQ8"
          strategy="afterInteractive"
        />
        <Script id="ga-script" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-DE486L9YQ8');
          `}
        </Script>
      </body>
    </html>
  );
}
