import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { ClientLayout } from "@/components/ClientLayout";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const jetbrainsMono = JetBrains_Mono({ variable: "--font-jetbrains-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyEnum Digital Agency - Software, Website & Digital Marketing in Dubai, Salem & Kerala",
  description:
    "MyEnum Digital Agency delivers professional software development, website design, and digital marketing solutions. Complete business growth solutions under one roof.",
  keywords : [
    "web development salem",
"website development salem",
"web development company salem",
"website development company salem",
"web application development salem",
"web development services salem",
"frontend developer salem",
"backend developer salem",
"python web development salem",
"react development salem",
"node.js development salem",
"freelance web developer salem",
"ecommerce website development salem",
"web programming salem",
"web design and development salem",
"web dev salem",
"web development agency salem",
"website developer near me salem",
"web design near me salem",
"html5 development salem",
"css3 styling salem",
"database integration salem",
"custom web development salem",
"enterprise web solutions salem",
"web development packages salem",
"website pricing plans salem",
"web development firm salem",
"wordpress developer salem",
"local SEO web developer salem",
"best web development company salem",
"responsive web design salem",
"mobile web development salem",
"technology stack development salem",
"net developer salem",
"angular developer salem",
"vue.js developer salem",
"full stack developer salem",
"website redesign salem",
"maintenance web development salem",
"online presence salem",
"SEO for website salem",
"website optimization salem",
"custom ecommerce development salem",
"business website salem",
"industry web development salem",
"travel agency web development salem",
"construction company website salem",
"manufacturing company website salem",
"healthcare website development salem",
"educational website development salem",
"real estate web development salem",
"salem web consultant",
"web hosting services salem",
"domain registration salem",
"UI/UX design salem",
"mobile responsive website salem",
"cms website solutions salem",
"custom cms development salem",
"dynamic website development salem",
"static website development salem",
"React JS development salem",
"Node JS integration salem",
"API integration development salem",
"social media integration website salem",
"SEO expert salem",
"website marketing salem",
"digital marketing web development salem",
"Portfolio website development salem",
"product website development salem",
"B2B web development salem",
"B2C web development salem",
"salem landing page design",
"corporate profile website salem",
"company presentations website salem",
"web server hosting salem",
"SSL certificate setup salem",
"secure website development salem",
"web analytics salem",
"keywords ranking website salem",
"Google business profile optimization salem",
"local business website salem",
"bespoke website development salem",
"custom plugins development salem",
"WordPress optimization salem",
"MERN stack web development salem",
"UI frameworks salem",
"Bootstrap website salem",
"website content development salem",
"industry-specific web development salem",
"online booking website salem",
"appointment scheduling web development salem",
"shopify web development salem",
"Magento website development salem",
"WooCommerce website development salem",
"web portal development salem",
"progressive web app development salem",
"cloud hosting website salem",
"website support services salem",
"SEO audit website salem",
"site performance optimization salem",
"cross-platform web development salem",
"multilingual website development salem",
"custom dashboards website salem",
"web design for SMEs salem",
"web development salem",
"website development salem",
"web development company salem",
"website development company salem",
"web application development salem",
"web development services salem",
"frontend developer salem",
"backend developer salem",
"python web development salem",
"react development salem",
"node.js development salem",
"freelance web developer salem",
"ecommerce website development salem",
"web programming salem",
"web design and development salem",
"web dev salem",
"web development agency salem",
"website developer near me salem",
"web design near me salem",
"html5 development salem",
"css3 styling salem",
"database integration salem",
"custom web development salem",
"enterprise web solutions salem",
"web development packages salem",
"website pricing plans salem",
"web development firm salem",
"wordpress developer salem",
"local SEO web developer salem",
"best web development company salem",
"responsive web design salem",
"mobile web development salem",
"technology stack development salem",
"net developer salem",
"angular developer salem",
"vue.js developer salem",
"full stack developer salem",
"website redesign salem",
"maintenance web development salem",
"online presence salem",
"SEO for website salem",
"website optimization salem",
"custom ecommerce development salem",
"business website salem",
"industry web development salem",
"travel agency web development salem",
"construction company website salem",
"manufacturing company website salem",
"healthcare website development salem",
"educational website development salem",
"real estate web development salem",
"salem web consultant",
"web hosting services salem",
"domain registration salem",
"UI/UX design salem",
"mobile responsive website salem",
"cms website solutions salem",
"custom cms development salem",
"dynamic website development salem",
"static website development salem",
"React JS development salem",
"Node JS integration salem",
"API integration development salem",
"social media integration website salem",
"SEO expert salem",
"website marketing salem",
"digital marketing web development salem",
"Portfolio website development salem",
"product website development salem",
"B2B web development salem",
"B2C web development salem",
"salem landing page design",
"corporate profile website salem",
"company presentations website salem",
"web server hosting salem",
"SSL certificate setup salem",
"secure website development salem",
"web analytics salem",
"keywords ranking website salem",
"Google business profile optimization salem",
"local business website salem",
"bespoke website development salem",
"custom plugins development salem",
"WordPress optimization salem",
"MERN stack web development salem",
"UI frameworks salem",
"Bootstrap website salem",
"website content development salem",
"industry-specific web development salem",
"online booking website salem",
"appointment scheduling web development salem",
"shopify web development salem",
"Magento website development salem",
"WooCommerce website development salem",
"web portal development salem",
"progressive web app development salem",
"cloud hosting website salem",
"website support services salem",
"SEO audit website salem",
"site performance optimization salem",
"cross-platform web development salem",
"multilingual website development salem",
"custom dashboards website salem",
"web design for SMEs salem",
  "Digital Marketing near me Dubai",
  "Digital Marketing Dubai near me",
  "best Digital Marketing Dubai",
  "Digital Marketing best Dubai",
  "top Digital Marketing Dubai",
  "Digital Marketing top Dubai",
  "affordable Digital Marketing Dubai",
  "Digital Marketing affordable Dubai",
  "Digital Marketing packages Dubai",
  "Digital Marketing Dubai packages",
  "Digital Marketing agency Dubai",
  "Digital Marketing Dubai agency",
  "Digital Marketing company Dubai",
  "Digital Marketing Dubai company",
  "Digital Marketing services Dubai",
  "Digital Marketing Dubai services",
  "Digital Marketing expert Dubai",
  "Digital Marketing Dubai expert",
  "Digital Marketing consultant Dubai",
  "Digital Marketing Dubai consultant",
  "Digital Marketing solutions Dubai",
  "Digital Marketing Dubai solutions",

  // Software
  "Software near me Dubai",
  "Software Dubai near me",
  "best Software Dubai",
  "Software best Dubai",
  "top Software Dubai",
  "Software top Dubai",
  "affordable Software Dubai",
  "Software affordable Dubai",
  "Software packages Dubai",
  "Software Dubai packages",
  "Software agency Dubai",
  "Software Dubai agency",
  "Software company Dubai",
  "Software Dubai company",
  "Software services Dubai",
  "Software Dubai services",
  "Software expert Dubai",
  "Software Dubai expert",
  "Software consultant Dubai",
  "Software Dubai consultant",
  "Software solutions Dubai",
  "Software Dubai solutions",

  // Website
  "Website near me Dubai",
  "Website Dubai near me",
  "best Website Dubai",
  "Website best Dubai",
  "top Website Dubai",
  "Website top Dubai",
  "affordable Website Dubai",
  "Website affordable Dubai",
  "Website packages Dubai",
  "Website Dubai packages",
  "Website agency Dubai",
  "Website Dubai agency",
  "Website company Dubai",
  "Website Dubai company",
  "Website services Dubai",
  "Website Dubai services",
  "Website expert Dubai",
  "Website Dubai expert",
  "Website consultant Dubai",
  "Website Dubai consultant",
  "Website solutions Dubai",
  "Website Dubai solutions",

  // --- Salem variations ---
  // Digital Marketing
  "Digital Marketing near me Salem",
  "Digital Marketing Salem near me",
  "best Digital Marketing Salem",
  "Digital Marketing best Salem",
  "top Digital Marketing Salem",
  "Digital Marketing top Salem",
  "affordable Digital Marketing Salem",
  "Digital Marketing affordable Salem",
  "Digital Marketing packages Salem",
  "Digital Marketing Salem packages",
  "Digital Marketing agency Salem",
  "Digital Marketing Salem agency",
  "Digital Marketing company Salem",
  "Digital Marketing Salem company",
  "Digital Marketing services Salem",
  "Digital Marketing Salem services",
  "Digital Marketing expert Salem",
  "Digital Marketing Salem expert",
  "Digital Marketing consultant Salem",
  "Digital Marketing Salem consultant",
  "Digital Marketing solutions Salem",
  "Digital Marketing Salem solutions",

  // Software
  "Software near me Salem",
  "Software Salem near me",
  "best Software Salem",
  "Software best Salem",
  "top Software Salem",
  "Software top Salem",
  "affordable Software Salem",
  "Software affordable Salem",
  "Software packages Salem",
  "Software Salem packages",
  "Software agency Salem",
  "Software Salem agency",
  "Software company Salem",
  "Software Salem company",
  "Software services Salem",
  "Software Salem services",
  "Software expert Salem",
  "Software Salem expert",
  "Software consultant Salem",
  "Software Salem consultant",
  "Software solutions Salem",
  "Software Salem solutions",

  // Website
  "Website near me Salem",
  "Website Salem near me",
  "best Website Salem",
  "Website best Salem",
  "top Website Salem",
  "Website top Salem",
  "affordable Website Salem",
  "Website affordable Salem",
  "Website packages Salem",
  "Website Salem packages",
  "Website agency Salem",
  "Website Salem agency",
  "Website company Salem",
  "Website Salem company",
  "Website services Salem",
  "Website Salem services",
  "Website expert Salem",
  "Website Salem expert",
  "Website consultant Salem",
  "Website Salem consultant",
  "Website solutions Salem",
  "Website Salem solutions",

  // --- Kerala variations ---
  // Digital Marketing
  "Digital Marketing near me Kerala",
  "Digital Marketing Kerala near me",
  "best Digital Marketing Kerala",
  "Digital Marketing best Kerala",
  "top Digital Marketing Kerala",
  "Digital Marketing top Kerala",
  "affordable Digital Marketing Kerala",
  "Digital Marketing affordable Kerala",
  "Digital Marketing packages Kerala",
  "Digital Marketing Kerala packages",
  "Digital Marketing agency Kerala",
  "Digital Marketing Kerala agency",
  "Digital Marketing company Kerala",
  "Digital Marketing Kerala company",
  "Digital Marketing services Kerala",
  "Digital Marketing Kerala services",
  "Digital Marketing expert Kerala",
  "Digital Marketing Kerala expert",
  "Digital Marketing consultant Kerala",
  "Digital Marketing Kerala consultant",
  "Digital Marketing solutions Kerala",
  "Digital Marketing Kerala solutions",

  // Software
  "Software near me Kerala",
  "Software Kerala near me",
  "best Software Kerala",
  "Software best Kerala",
  "top Software Kerala",
  "Software top Kerala",
  "affordable Software Kerala",
  "Software affordable Kerala",
  "Software packages Kerala",
  "Software Kerala packages",
  "Software agency Kerala",
  "Software Kerala agency",
  "Software company Kerala",
  "Software Kerala company",
  "Software services Kerala",
  "Software Kerala services",
  "Software expert Kerala",
  "Software Kerala expert",
  "Software consultant Kerala",
  "Software Kerala consultant",
  "Software solutions Kerala",
  "Software Kerala solutions",

  // Website
  "Website near me Kerala",
  "Website Kerala near me",
  "best Website Kerala",
  "Website best Kerala",
  "top Website Kerala",
  "Website top Kerala",
  "affordable Website Kerala",
  "Website affordable Kerala",
  "Website packages Kerala",
  "Website Kerala packages",
  "Website agency Kerala",
  "Website Kerala agency",
  "Website company Kerala",
  "Website Kerala company",
  "Website services Kerala",
  "Website Kerala services",
  "Website expert Kerala",
  "Website Kerala expert",
  "Website consultant Kerala",
  "Website Kerala consultant",
  "Website solutions Kerala",
  "Website Kerala solutions",
  "website development company in Salem",
  "best website development company Salem",
  "top web design company Salem",
  "affordable web design Salem",
  "professional website design Salem",
  "ecommerce website development Salem",
  "custom website design Salem",
  "WordPress website development Salem",
  "business website design Salem",
  "corporate website design Salem",
  "website redesign services Salem",
  "responsive website design Salem",
  "static website development Salem",
  "dynamic website development Salem",
  "small business website design Salem",
  "web hosting services Salem",
  "domain registration Salem",
  "SEO friendly website design Salem",
  "UI UX design company Salem",
  "mobile friendly website design Salem",
  "digital marketing agency in Salem",
  "best digital marketing company Salem",
  "top digital marketing services Salem",
  "affordable digital marketing Salem",
  "SEO services in Salem",
  "local SEO services Salem",
  "search engine optimization Salem",
  "SEO expert in Salem",
  "PPC advertising company Salem",
  "Google Ads service Salem",
  "Facebook ads expert Salem",
  "Instagram marketing agency Salem",
  "YouTube marketing services Salem",
  "social media marketing agency Salem",
  "SMM company in Salem",
  "content marketing agency Salem",
  "email marketing services Salem",
  "digital branding company Salem",
  "branding and digital marketing Salem",
  "online marketing services Salem",
  "digital strategy consulting Salem",
  "digital marketing consultant Salem",
  "digital transformation services Salem",
  "online reputation management Salem",
  "ORM services Salem",
  "performance marketing agency Salem",
  "lead generation services Salem",
  "affiliate marketing services Salem",
  "growth marketing company Salem",
  "startup digital marketing Salem",
  "digital marketing for businesses Salem",
  "digital advertising company Salem",
  "digital promotions Salem",
  "ecommerce SEO services Salem",
  "ecommerce marketing company Salem",
  "Google my business optimization Salem",
  "local business online marketing Salem",
  "IT company in Salem",
  "top IT solutions Salem",
  "software development company Salem",
  "mobile app development company Salem",
  "Android app development Salem",
  "iOS app development Salem",
  "custom app development Salem",
  "hybrid app development Salem",
  "web application development Salem",
  "CRM software development Salem",
  "ERP software solutions Salem",
  "custom software development Salem",
  "IT consulting company Salem",
  "graphic design services Salem",
  "creative design company Salem",
  "logo design company Salem",
  "branding services Salem",
  "brochure design Salem",
  "flyer design company Salem",
  "digital creatives company Salem",
  "UI UX design services Salem",
  "video marketing services Salem",
  "motion graphics company Salem",
  "animation services Salem",
  "explainer video services Salem",
  "corporate video production Salem",
  "website maintenance company Salem",
  "IT support services Salem",
  "cloud hosting services Salem",
  "cybersecurity company Salem",
  "data analytics company Salem",
  "AI solutions company Salem",
  "marketing automation services Salem",
  "conversion rate optimization Salem",
  "sales funnel marketing Salem",
  "local business SEO Salem",
  "digital marketing near me Salem",
  "website design near me Salem",
  "IT services near me Salem",
  "best web developers in Salem",
  "top digital marketers Salem",
  "website company near me Salem",
  "SEO company near me Salem",
    
  "website development Kerala",
 "website designers Kerala",
 "website design company Kerala",
 "website services Kerala",
 "web development Kerala",
 "web design Kerala",
 "web development company Kerala",
 "custom website development Kerala",
 "business website Kerala",
 "ecommerce website Kerala",
 "professional website Kerala",
 "corporate website Kerala",
 "responsive web design Kerala",
 "dynamic website Kerala",
 "static website Kerala",
 "cheap website Kerala",
 "affordable website Kerala",
 "top website designers Kerala",
 "best website company Kerala",
 "freelance web designer Kerala",
 "startup website Kerala",
 "portfolio website Kerala",
 "landing page design Kerala",
 "wordpress website Kerala",
 "shopify website Kerala",
 "magento website Kerala",
 "joomla website Kerala",
 "cms website Kerala",
 "travel website Kerala",
 "hotel website Kerala",
 "restaurant website Kerala",
 "real estate website Kerala",
 "school website Kerala",
 "college website Kerala",
 "university website Kerala",
 "church website Kerala",
 "hospital website Kerala",
 "clinic website Kerala",
 "doctor website Kerala",
 "law firm website Kerala",
 "NGO website Kerala",
 "government website Kerala",
 "personal website Kerala",
 "blog website Kerala",
 "news portal Kerala",
 "classified website Kerala",
 "job portal Kerala",
 "directory website Kerala",
 "auction website Kerala",
 "booking website Kerala",
 "custom web portal Kerala",
 "web app Kerala",
 "progressive web app Kerala",
 "app integration Kerala",
 "mobile friendly website Kerala",
 "modern website design Kerala",
 "minimal website Kerala",
 "SEO friendly website Kerala",
 "software company Kerala",
 "software development Kerala",
 "custom software Kerala",
 "software development company Kerala",
 "software solutions Kerala",
 "business software Kerala",
 "ERP software Kerala",
 "CRM software Kerala",
 "accounting software Kerala",
 "hospital software Kerala",
 "school management software Kerala",
 "HR software Kerala",
 "POS software Kerala",
 "billing software Kerala",
 "inventory software Kerala",
 "cloud software Kerala",
 "retail software Kerala",
 "pharma software Kerala",
 "logistics software Kerala",
 "manufacturing software Kerala",
 "project management software Kerala",
 "AI software Kerala",
 "machine learning software Kerala",
 "automation software Kerala",
 "mobile app development Kerala",
 "android app development Kerala",
 "iOS app development Kerala",
 "app development Kerala",
 "cross platform apps Kerala",
 "hybrid app development Kerala",
 "flutter app development Kerala",
 "react native apps Kerala",
 "native apps Kerala",
 "UI UX design Kerala",
 "user interface design Kerala",
 "user experience Kerala",
 "prototyping Kerala",
 "wireframing Kerala",
 "product design Kerala",
 "digital marketing Kerala",
 "SEO services Kerala",
 "local SEO Kerala",
 "social media marketing Kerala",
 "branding services Kerala",
 "online marketing Kerala",
 "search engine optimization Kerala",
 "Google ads Kerala",
 "PPC services Kerala",
 "content marketing Kerala",
 "email marketing Kerala",
 "facebook ads Kerala",
 "instagram marketing Kerala",
 "linkedin marketing Kerala",
 "twitter marketing Kerala",
 "youtube marketing Kerala",
 "influencer marketing Kerala",
 "digital branding Kerala",
 "ORM services Kerala",
 "reputation management Kerala",
 "video marketing Kerala",
 "ecommerce marketing Kerala",
 "affiliate marketing Kerala",
 "digital strategy Kerala",
 "IT company Kerala",
 "IT services Kerala",
 "IT solutions Kerala",
 "IT consultancy Kerala",
 "IT outsourcing Kerala",
 "IT support Kerala",
 "IT infrastructure Kerala",
 "cloud services Kerala",
 "server management Kerala",
 "network solutions Kerala",
 "data security Kerala",
 "cybersecurity Kerala",
 "blockchain development Kerala",
 "AI development Kerala",
 "ML development Kerala",
 "data science Kerala",
 "big data solutions Kerala",
 "IoT solutions Kerala",
 "SaaS development Kerala",
 "PaaS services Kerala",
 "IT automation Kerala",
 "software testing Kerala",
 "QA services Kerala",
 "devops Kerala",
 "system integration Kerala",
 "BNI Kerala",
 "BNI business networking Kerala",
 "BNI software Kerala",
 "BNI website Kerala",
 "BNI IT company Kerala",
 "BNI networking Kerala",
 "BNI members Kerala",
 "BNI entrepreneurs Kerala",
 "BNI business growth Kerala",
 "BNI chapter Kerala",
 "BNI meetings Kerala",
 "BNI events Kerala",
 "BNI startup Kerala",
 "BNI business Kerala",
 "BNI Kerala IT services",
 "BNI Kerala software solutions",
 "BNI Kerala website development",
 "BNI Kerala networking platform",
 "BNI company growth Kerala",
 "BNI entrepreneurs network Kerala",
 "BNI business referrals Kerala",
 "BNI corporate connections Kerala",
 "BNI digital Kerala",
 "BNI IT Kerala",
 "BNI technology Kerala",
 "BNI partnership Kerala",
 "BNI collaboration Kerala",
 "BNI startup ecosystem Kerala",
 "BNI software development Kerala",
 "BNI marketing Kerala",
 "BNI business circle Kerala",
 "BNI chapter meetings Kerala",
 "BNI events 2025 Kerala",
 "BNI Trivandrum Kerala",
 "BNI Kochi Kerala",
 "BNI Calicut Kerala",
 "BNI networking hub Kerala",
 "BNI entrepreneurs Kerala",
 "BNI global Kerala",
 "BNI innovation Kerala",
 "BNI digital solutions Kerala",
 "BNI Kerala technology solutions",
 "BNI Kerala IT consultancy",
 "BNI Kerala startup network",
 "BNI Kerala professionals",
 "BNI Kerala entrepreneurs club",
 "BNI Kerala business community",
 "BNI Kerala growth opportunities",
 "BNI Kerala collaborations",
 "BNI Kerala events",
 "BNI Kerala IT startups",
 "BNI Kerala software industry",
 "BNI Kerala business referrals",
],
  openGraph: {
    title: "MyEnum Digital Agency",
    description:
      "Professional software, website, and digital marketing solutions in Dubai, Salem & Kerala",
    url: "https://www.myenum.com", // replace with your live URL
    siteName: "MyEnum",
    images: [
      {
        url: "https://www.myenum.com/og-image.png", // replace with your OG image
        width: 1200,
        height: 630,
        alt: "MyEnum Digital Agency",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MyEnum Digital Agency",
    description:
      "Professional software, website, and digital marketing solutions in Dubai, Salem & Kerala",
    images: ["https://www.myenum.com/og-image.png"], // replace with your OG image
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable} antialiased dark text-slate-50`}>
      <body>
        <ClientLayout>{children}</ClientLayout>

        {/* Microsoft Clarity */}
        <Script id="clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "svumhdjdy5");
          `}
        </Script>

        {/* Google Analytics */}
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-DE486L9YQ8" strategy="afterInteractive" />
        <Script id="ga-script" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-DE486L9YQ8');
          `}
        </Script>
      </body>
    </html>
  );
}
