import SeoHead from '@/components/SeoHead';
import Features from '@/components/features-12';
import { GlowingTable } from '@/components/GlowingTable';
import HeroSection from '@/components/hero-section';
import IntegrationsSection from '@/components/integrations-8';
import LogoCloud from '@/components/logo-cloud';
import TeamSection from '@/components/team';
import CTA2 from '@/components/mvpblocks/cta-2';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'MyEnum Agency | Best Software Development Company India & Global',
  description: 'Transform your digital presence with MyEnum Agency. Expert software development, custom websites, mobile apps, SaaS products, and digital marketing services. 500+ projects delivered globally. Get free quote today!',
  keywords: [
    'MyEnum Agency',
    'software development',
    'website development',
    'digital marketing',
    'mobile app development',
    'custom software',
    'SaaS development',
    'web development',
    'digital transformation',
    'business solutions',
    'start your project',
    'book free consultation',
    'digital presence',
    'software company',
    'digital agency',
    'IT company',
    'development company',
    'software development company',
    'web development company',
    'digital marketing company',
    'mobile app development company',
    'best software company',
    'top software company',
    'leading software company',
    'software development agency',
    'web development agency',
    'digital marketing agency',
    'custom software development',
    'enterprise software',
    'startup solutions',
    'business software',
    'SMB software',
    'small business software',
    'digital solutions',
    'technology solutions',
    'innovation',
    'digital innovation',
    'tech company',
    'software firm',
    'development firm',
    'technology partner',
    'IT partner',
    'digital partner',
    'software vendor',
    'development vendor',
    'India software company',
    'software company India',
    'software company Chennai',
    'software company Bangalore',
    'software company Hyderabad',
    'software company Mumbai',
    'software company Delhi',
    'software company Kerala',
    'software company Salem',
    'software company Coimbatore',
    'web development India',
    'digital marketing India',
    'mobile app India',
    'SaaS product India',
    'software services',
    'web services',
    'digital services',
    'development services',
    'IT services',
    'consulting services',
    'software consulting',
    'IT consulting',
    'digital consulting',
    'project development',
    'custom development',
    'offshore development',
    'outsourcing',
    'software outsourcing',
    'offshore software',
    'dedicated team',
    'development team',
    'expert developers',
    'skilled developers',
    'professional developers',
    'experienced team',
    'quality software',
    'reliable software',
    'secure software',
    'scalable software',
    'modern software',
    'innovative software',
    'cutting-edge technology',
    'latest technology',
    'modern technology',
    'advanced software',
    'future-ready',
    'digital-ready',
    'AI development',
    'ML development',
    'artificial intelligence',
    'machine learning',
    'cloud solutions',
    'cloud development',
    'AWS development',
    'Azure development',
    'Google Cloud',
    'UI UX design',
    'graphic design',
    'logo design',
    'branding',
    'brand identity',
    'e-commerce development',
    'e-commerce website',
    'online store',
    'e-commerce solutions',
    'ecommerce platform',
    'shopify development',
    'woocommerce development',
    'wordpress development',
    'CMS development',
    'content management',
    'SEO services',
    'search engine optimization',
    'PPC advertising',
    'Google Ads',
    'Facebook marketing',
    'social media marketing',
    'Instagram marketing',
    'LinkedIn marketing',
    'content marketing',
    'email marketing',
    'video marketing',
    'influencer marketing',
    'digital advertising',
    'online marketing',
    'internet marketing',
    'marketing automation',
    'lead generation',
    'conversion optimization',
    'ROI optimization',
    'analytics',
    'data analytics',
    'big data',
    'data science',
    'IoT development',
    'blockchain development',
    'cybersecurity',
    'IT security',
    'API development',
    'integration services',
    'database development',
    'backend development',
    'frontend development',
    'full stack development',
    'React development',
    'Node.js development',
    'Python development',
    'Java development',
    'PHP development',
    'Angular development',
    'Vue development',
    'Flutter development',
    'React Native development',
    'iOS development',
    'Android development',
    'cross-platform development',
    'hybrid app development',
    'native app development',
    'app store optimization',
    'ASO',
    'healthcare software',
    'hospital management',
    'clinic software',
    'doctor software',
    'education software',
    'real estate software',
    'finance software',
    'logistics software',
    'retail software',
    'manufacturing software',
    'restaurant software',
    'hotel software',
    'appointment booking',
    'CRM development',
    'ERP development',
    'accounting software',
    'inventory software',
    'project management',
    'business automation',
    'workflow automation',
    'process automation',
    'digital transformation',
    'business growth',
    'revenue growth',
    'increase sales',
    'boost sales',
    'grow business',
    'scale business',
    'expand business',
    'digital expansion',
    'market expansion',
    'new markets',
    'global expansion',
    'international clients',
    'global clients',
    'trusted by clients',
    'client satisfaction',
    'successful projects',
    'project completion',
    'on-time delivery',
    'quality delivery',
    'professional service',
    'expert service',
    'premium service',
    'best service',
    'top service',
    'quality service',
    'reliable service',
    'consistent service',
    'dedicated support',
    '24/7 support',
    'technical support',
    'customer support',
    'maintenance support',
    'ongoing support',
    'post-development support',
    'lifetime support',
    'free consultation',
    'get quote',
    'request quote',
    'free quote',
    'no obligation quote',
    'quick quote',
    'instant quote',
    'competitive pricing',
    'affordable pricing',
    'transparent pricing',
    'no hidden costs',
    'value for money',
    'best value',
    'ROI',
    'return on investment',
    'business ROI',
    'success partnership',
    'long-term partnership',
    'strategic partnership',
    'mutual growth',
    'collaboration',
    'team collaboration',
  ],
  openGraph: {
    title: 'MyEnum Agency | Best Software Development Company India & Global',
    description: 'Transform your digital presence with MyEnum Agency. Expert software development, custom websites, mobile apps, SaaS products, and digital marketing services.',
    url: 'https://myenum.in/',
    siteName: 'MyEnum Agency',
    images: [
      {
        url: '/iconc.webp',
        width: 1200,
        height: 630,
        alt: 'MyEnum Agency - Software Development & Digital Marketing',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'MyEnum Agency | Best Software Development Company India & Global',
    description: 'Transform your digital presence with MyEnum Agency. Expert software development, custom websites, mobile apps, SaaS products, and digital marketing services.',
  },
  alternates: {
    canonical: 'https://myenum.in/',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function Home() {
  return (
    <>
      <SeoHead
        title="MyEnum Agency - Advanced SaaS Solutions & Software Development"
        description="MyEnum Agency offers advanced SaaS solutions, custom software development, and digital transformation services for businesses. Contact us today!"
        keywords="SaaS solutions, software development, MyEnum Agency, digital transformation, business solutions, web app development"
        canonicalUrl="https://myenum.in/"
      />

      <main className="overflow-hidden">
        <HeroSection />
        <LogoCloud />
        <Features />
        <GlowingTable />
        <IntegrationsSection />
        <TeamSection />
        <CTA2 />
      </main>
    </>
  );
}
