// src/seo/defaultKeywords.ts
// Centralised list of keywords that should appear on every page.
export const GLOBAL_DEFAULT_KEYWORDS = [
  "website develop agency",
  "website development agency",
  "website development agency near me",
  "website development agency in india",
  "website development agency in dubai",
  "website development agency in delhi",
  "website development agency in mumbai",
  "website development agency website template",
  "website development agency in kolkata",
  "website development agency in usa",
  "website development agency london",
  "website development agency website design",
  "website development agency in bangalore",
  "website development agency in pune",
  "website development agency in noida",
  "website development agency in jaipur",
  "website development agency australia",
  "website development agency ads",
  "website development agency ahmedabad",
  "web development agency australia",
  "web development agency abu dhabi",
  "web development agency athens",
  "web development agent ai",
  "website design agency ahmedabad",
  "website design agency australia",
  "website design agency auckland",
  "website design agency akola",
  "website design agency ameerpet",
  "web design agency amsterdam",
  "web design agency abu dhabi",
  "web design agency atlanta",
  "website development agency bangalore",
  "website development agency bangladesh",
  "web development agency berlin",
  "web development agency big ambitions",
  "web development agency birmingham",
  "web development agency bristol",
  "web development agency banner",
  "web development agency brisbane",
  "web development agency brochure",
  "web development agency business model",
  "web development agency blog",
  "web development agency business plan",
  "website design agency bangalore",
  "website design agency brighton",
  "website design agency birmingham",
  "website development agency canada",
  "website development agency chennai",
  "web development agency chicago",
  "web development agency california",
  "web development agency careers",
  "web development agency course",
  "web development agency canberra",
  "web development agency calgary",
  "website design agency cape town",
  "website design agency california",
  "website design agency canada",
  "website design agency chicago",
  "website design agency canberra",
  "web design agency cardiff",
  "web design agency coventry",
  "website development agency design",
  "website development agency dubai",
  "website development agency delhi",
  "web development agency dublin",
  "website design agency dubai",
  "website design agency dublin",
  "website design agency darwin",
  "website design agency delhi",
  "web design agency dallas",
  "web design agency denver",
  "web design agency derby",
  "web design agency directory",
  "web development digital agency",
  "website development agency in dehradun",
  "web design digital agency",
  "website development agency egypt",
  "web development agency europe",
  "web design agency essex",
  "web design agency egypt",
  "web design agency edinburgh",
  "web design agency europe",
  "web design agency exeter",
  "web design agency england",
  "web design agency edmonton",
  "web design agency examples",
  "web design agency eastbourne",
  "web design agency website examples",
  "oxence web design agency elementor wordpress theme",
  "umi web design agency elementor template kit",
  "maser web design agency elementor template kit",
  "website development agency for b2b companies in mumbai",
  "website development agency for b2b companies",
  "website development agency for b2b companies in india",
  "website development agency for schools in lucknow",
  "web development agency for sale",
  "web development agency florida",
  "web development agency figma",
  "web development agency figma template",
  "web development agency for startups",
  "web development agency for retail",
  "web development agency france",
  "website design agency for coaches",
  "web design agency florida",
  "web design agency for sale",
  "web design agency for small businesses",
  "web development agency glasgow",
  "web development agency germany",
  "web development agency gurgaon",
  "web development agency github",
  "website design agency gurgaon",
  "web design agency glasgow",
  "web design agency gold coast",
  "web design agency germany",
  "web design agency galway",
  "web design agency ghaziabad",
  "web design agency guildford",
  "web development agency website github",
  "website development agency in gujarat",
  "web development agency in greater noida",
  "web development agency in ghana",
  "web development agency hiring",
  "web development agency html template",
  "website design agency hyderabad",
  "web design agency hampshire",
  "web design agency hiring",
  "web design agency houston",
  "web design agency html template",
  "web design agency hong kong",
  "web design agency hull",
  "web design agency huddersfield",
  "web design agency hero section",
  "web design agency hamilton",
  "web design agency haslingden",
  "web design agency harrogate",
  "web design agency hungary",
  "website development agency in uk",
  "website development agency in surat",
  "website development agency in canada",
  "website development agency in navi mumbai",
  "website development agency in varanasi",
  "website development agency jammu",
  "web developer agency jobs",
  "web development agency jaipur",
  "website design agency jammu",
  "website design agency jobs",
  "web design agency johannesburg",
  "web design agency in japan",
  "website development agency in jakarta",
  "web development agency in jodhpur",
  "website design agency in jaipur",
  "web design agency new jersey",
  "jewelry website development agency",
  "best website development agency in jaipur",
  "web development agency kolkata",
  "web development agency kalighat metro",
  "web development agency kerala",
  "web development agency karachi",
  "web design agency kildare",
  "web design agency kellyville",
  "web design agency kent",
  "web design agency kochi",
  "web design agency kuwait",
  "web design agency kenya",
  "web design agency kolkata",
  "web design agency karachi",
  "website development agency in kanpur",
  "website development agency in kochi",
  "web development agency in kenya",
  "website development agency logo",
  "website development agency landing page",
  "web development agency london",
  "web development agency los angeles",
  "web development agency leeds",
  "web development agency landing page",
  "web development agency lebanon",
  "web development agency lahore",
  "web development agency liverpool",
  "web development agency linkedin",
  "web development agency ludhiana",
  "web development agency list",
  "web development agency landing page template",
  "web development agency london ontario",
  "website development agency mumbai",
  "website development agency mauritius",
  "website development agency melbourne",
  "website development agency manchester",
  "web development agency melbourne",
  "web development agency malaysia",
  "web development agency montreal",
  "web development agency morocco",
  "web development agency meaning",
  "web development agency miami",
  "web development agency mauritius",
  "website design agency melbourne",
  "website design agency malaysia",
  "website design agency mumbai",
  "website design agency manchester",
  "website development agency noida",
  "web development agency near me",
  "web development agency new york",
  "web development agency name ideas",
  "web development agency names",
  "web development agency nyc",
  "web development agency near kalighat metro",
  "web development agency newcastle",
  "website design agency near me",
  "website design agency new york",
  "website design agency nyc",
  "website design agency noida",
  "website design agency nigeria",
  "web design agency near me",
  "web development agency ottawa",
  "web design agency oü",
  "web design agency ottawa",
  "web design agency oxford",
  "web design agency orlando",
  "web design agency oman",
  "web design agency owner",
  "web design agency ontario",
  "web design agency omaha ne",
  "website development agency in okhla",
  "web design agency london ontario",
  "online travel agency website development",
  "website development agency pune",
  "website development agency pakistan",
  "web development agency portfolio",
  "web development agency philippines",
  "web development agency pricing",
  "web development agency perth",
  "web development agency poland",
  "web development agency poster",
  "website design agency perth",
  "website design agency portfolio",
  "website design agency pricing",
  "website design agency pune",
  "website building agency panchkula",
  "website design agency philippines",
  "web design agency parramatta",
  "web development agency qatar",
  "website design agency quote",
  "web design agency qatar",
  "website development questions",
  "website development quora",
  "website development agency reddit",
  "web development agency riyadh",
  "website design agency reddit",
  "web design agency richmond",
  "web design agency rossendale",
  "web design agency reading",
  "web design agency romania",
  "web design agency riyadh",
  "web design agency rawtenstall",
  "web design agency revenue",
  "web design agency raleigh",
  "web design agency remote",
  "web developer recruitment agency",
  "website development agency in ranchi",
  "website development agency in raipur",
  "website development agency surat",
  "website development agency sydney",
  "website development agency services",
  "web development agency singapore",
  "web development agency san francisco",
  "web development agency saudi arabia",
  "web development agency seattle",
  "web development agency sg",
  "web development agency san diego",
  "web development agency south africa",
  "web development agency sri lanka",
  "web development agency startup",
  "web development agent skills",
  "website design agency sydney",
  "website design agency singapore",
  "website development agency template",
  "website development agency theme",
  "web development agency toronto",
  "web development agency theme wordpress",
  "web development agency texas",
  "web development agency template free",
  "web development agency themeforest",
  "website design agency toronto",
  "website design agency template",
  "website design agency theme",
  "web design agency texas",
  "web design agency tampa",
  "web design agency thailand",
  "web design agency template wordpress",
  "web design agency themeforest",
  "website development agency uk",
  "website development agency usa",
  "web development agency usa",
  "web development agency uk",
  "web development agency uae",
  "web development agency upwork",
  "web development agency ui",
  "website design agency uk",
  "website design agency usa",
  "website design agency uae",
  "website creation agency us",
  "web design agency ukraine",
  "web design agency ui",
  "website development agency in udaipur",
  "best website development agency in usa",
  "web development agency vancouver",
  "web development agency vietnam",
  "website design agency vancouver",
  "web design agency vietnam",
  "web design agency vienna",
  "web design agency virginia beach",
  "web design agency virginia",
  "website development agency in vadodara",
  "website development agency in vasai",
  "website design agency in varanasi",
  "web - design - agency in vadodara",
  "web design agency promo video after effects template",
  "web design agency northern virginia",
  "web design agency promo video",
  "website development agency wordpress theme",
  "web development agency wordpress",
  "website design agency wordpress theme",
  "web design agency wilmslow",
  "web design agency washington dc",
  "web design agency winnipeg",
  "web design agency wordpress template",
  "web design agency wordpress",
  "web design agency webflow",
  "website design agency in west delhi",
  "web development agency website",
  "web development agency website template",
  "haptic web design agency wordpress theme",
  "website development agency india",
  "web design agency york",
  "web design agency yorkshire",
  "web design agency new york city",
  "national youth development agency website",
  "website development companies",
  "web design agency zurich",
  "web design agency new zealand",
  "website development agency in new zealand",
  "zambia development agency website",
  "website development company ahmedabad",
  "website development company abu dhabi",
  "website development company australia",
  "website development company aurangabad",
  "website development company in agra",
  "website development company in ambala",
  "website development company in amritsar",
  "website development company saudi arabia",
  "best website development company ahmedabad",
  "website development company bangalore",
  "website development company bhubaneswar",
  "website development company bhopal",
  "website development company bangladesh",
  "website development company bareilly",
  "website development company brochure",
  "website development company blog",
  "website development agency in bhopal",
  "website development company coimbatore",
  "website development company chennai",
  "website development company chandigarh",
  "website development company kochi",
  "website development company california",
  "website development company canada",
  "website development company calgary",
  "website development company calicut",
  "website development agency in chandigarh",
  "shopify website development company chennai",
  "website designing agency in chennai",
  "website development company in chicago",
  "ecommerce website development company coimbatore",
  "website development company dubai",
  "website development company delhi",
  "website development company delhi ncr",
  "website development company in dhaka",
  "website development company in dwarka",
  "website development company in durgapur",
  "shopify website development company delhi",
  "ecommerce website development company delhi",
  "best website development company delhi",
  "best website development company dubai",
  "website development company in europe",
  "website development company in ethiopia",
  "website development company in erode",
  "website development company for educational institutions",
  "website design agency in egypt",
  "ecommerce website development agency in ahmedabad",
  "website development company faridabad",
  "website development company for sale",
  "website development company for hotels in jaipur",
  "website design for agency",
  "website development agency in faridabad",
  "website development for company",
  "website designing agency in faridabad",
  "website development company in florida",
  "website development company in fujairah",
  "website development company ghaziabad",
  "website development company gujarat",
  "website development company guwahati",
  "website development agency in gurugram",
  "website development company in gorakhpur",
  "website development company in gwalior",
  "website development company in greater noida",
  "website development company in goa",
  "website development company in gaya",
  "website development company in germany",
  "website development company in gandhinagar",
  "website designing agency in gwalior",
  "website development company in ghana",
  "website development company hyderabad",
  "website development company hubli dharwad",
  "website development company html template",
  "website development company haridwar",
  "website development agency in hyderabad",
  "website development company in haryana",
  "website development company in haldwani",
  "website development company in hosur",
  "website development company in howrah",
  "website development company in hubli",
  "website development company in hanumangarh",
  "website development company in hsr layout",
  "website development company in houston",
  "website development company in hadapsar",
  "website development agency in uae",
  "website development company in bangalore",
  "website development company in delhi",
  "website development company jaipur",
  "website development company jobs",
  "website development company jabalpur",
  "website development company justdial",
  "website development company in jodhpur",
  "website development company in jalandhar",
  "website development company in janakpuri",
  "website development company in junagadh",
  "website development company in jamshedpur",
  "website development company in janakpuri delhi",
  "website development company kolkata",
  "website development company kerala",
  "website development company kanpur",
  "website development company karachi",
  "website development company kuwait",
  "website development company kolhapur",
  "website development agency in kerala",
  "website development agency in karachi",
  "website development company in kota",
  "website development company in kannur",
  "website design agency in kolkata",
  "website design agency london",
  "website development company lucknow",
  "website development company london",
  "website development company logo",
  "website development company los angeles",
  "website development company ludhiana",
  "website development company list",
  "website design agency los angeles",
  "website design agency landing page",
  "website design agency logo",
  "website design agency leeds",
  "website development company landing page",
  "website development company mumbai",
  "website development company mauritius",
  "website development company malaysia",
  "website development company melbourne",
  "website development company mohali",
  "website design agency mauritius",
  "website development company madurai",
  "website design agency minneapolis",
  "website development company near me",
  "website development company new york",
  "website development company noida",
  "website development company name ideas",
  "website development company nagpur",
  "website development company near gurugram haryana",
  "website development company names",
  "website development company nashik",
  "website creation agency near me",
  "website development company near lahore",
  "website development company nyc",
  "website development company oman",
  "website development company online",
  "website development company ottawa",
  "website development outsourcing company",
  "website development company in okhla",
  "website development company in odisha",
  "website development company pune",
  "website development company pakistan",
  "website development company portfolio",
  "website development company phoenix",
  "website development company poster",
  "website development company palanpur",
  "website development company patna",
  "website development company profile pdf",
  "website development company profile",
  "website development company philippines",
  "website development company qatar",
  "website development company rohini",
  "website development company rajkot",
  "website development company riyadh",
  "website development company in ranchi",
  "website development company in raipur",
  "shopify website design agency ravedigital agency",
  "website development company in rohini delhi",
  "website development company in rajasthan",
  "website development company in rishikesh",
  "website development company in rawalpindi",
  "website development company in roorkee",
  "website development company surat",
  "website development company singapore",
  "website design agency surat",
  "website development company sydney",
  "website design agency sunshine coast",
  "website development company softscribble pvt ltd",
  "website development company services",
  "website design agency seattle",
  "website development company sharjah",
  "website development company sri lanka",
  "website development company template",
  "website development company toronto",
  "website development company thrissur",
  "website development company templates free download",
  "website development company texas",
  "website development company theme",
  "website development company tirunelveli",
  "website development agency in tamilnadu",
  "website design travel agency",
  "website development agency in thane",
  "website development company in thane",
  "website development company usa",
  "website development company uk",
  "website development company uae",
  "website development company in udaipur",
  "website development company in uganda",
  "website development company in uttam nagar",
  "website development company in uttara",
  "website development company vadodara",
  "website development company vidhyadhar nagar",
  "website development company visiting card",
  "website development company in varanasi",
  "website development company in vasai",
  "website development company in vaishali",
  "website development company in vellore",
  "website development company in vizag",
  "website development company in vashi",
  "website development company in vijayawada",
  "website development agency website",
  "wordpress website development agency",
  "web website development agency",
  "website development agency in new york",
  "website development company in yamunanagar",
  "website development company in zirakpur",
  "website design company near me",
  "website creation company near me",
  "best website development company near me",
  "best website design agency near me",
  "top website development company near me",
  "shopify website development company near me",
  "ecommerce website design company near me",
  "website design and development company near me",
  "top website designing company near me",
  "web development company near me",
  "web development company near by me",
  "what is the average cost of website development",
  "where to hire someone to build a website",
  "websites to buy puppies near me",
  "web development agencies near me",
  "website development services near me",
  "website development company in near me",
  "website development company in trichy",
  "local web designers near me",
  "website development company near johar town lahore",
  "website developer job near me",
  "lab sites near me",
  "website developer near me",
  "website development company in india",
  "website designing agency in india",
  "best website development agency in india",
  "top website development agency in india",
  "wordpress website development agency in india",
  "shopify website development agency in india",
  "best website development company in india",
  "ecommerce website development company in india",
  "top website development company in india",
  "wordpress website development company in india",
  "shopify website development company in india",
  "php website development company in india",
  "travel website development company in india",
  "website design & development company in india",
  "custom website development company in india",
  "astrology website development company in india",
  "ai website development company in india",
  "website agency in india",
  "web development company in india banao technologies",
  "best website designing agency in india",
  "website development in india",
  "cheap website development company in india",
  "cms website development company in india",
  "web development companies in india",
  "website development cost in india",
  "website development india",
  "website designing company in delhi india",
  "bbb website designing company in delhi india",
  "web designing company in india fictionstar",
  "website development charges in india",
  "website designing company in hyderabad india",
  "hotel website development company in india",
  "healthcare website development company in india",
  "web development company in hyderabad india",
  "web designing company in india indore",
  "how to start a web development agency",
  "website development in karnataka",
  "website development in kerala",
  "leading website development company in india",
  "matrimonial website development company in india",
  "magento website development company in india",
  "dreamsoft infotech website development company in india noida",
  "ngo website development company in india",
  "news website development company in india",
  "web design agency names",
  "web development agency in new york",
  "invoidea mobile app & website development company in india photos",
  "invoidea mobile app & website development company in india reviews",
  "sustainable website development company in india",
  "static website development company in india",
  "website development services india",
  "web development agencies in india",
  "website designing agency in dubai",
  "best website development agency in dubai",
  "best website development company in dubai",
  "wordpress website development company in dubai",
  "top website development company in dubai",
  "best ecommerce website development company in dubai",
  "real estate website development company in dubai",
  "website design and development company in dubai",
  "squarespace web development agency in dubai",
  "web development company in dubai list",
  "web agency in dubai",
  "web development dubai",
  "dubai website development company",
  "dubai web agency",
  "dubai website developer",
  "web development companies in dubai",
  "digital marketing companies in uae",
  "website development in dubai",
  "enum digital website development & digital marketing agency in dubai",
  "web development companies in uae",
  "website development in uae",
  "web designer dubai",
  "digital marketing companies in dubai",
  "web designer salary in uae",
  "web designer salary in dubai",
  "website designing company in dubai",
  "web design dubai",
  "best website designing company in dubai",
  "website development agency in delhi ncr",
  "website development company in delhi ncr",
  "website designing agency in delhi",
  "website designing agency in delhi ncr",
  "best website development agency in delhi",
  "best website development company in delhi",
  "ecommerce website development company in delhi",
  "shopify website development company in delhi",
  "best website development company in delhi ncr",
  "wordpress website development company in delhi",
  "top website development company in delhi",
  "website development company in south delhi",
  "php website development company in delhi",
  "affordable website development company in delhi",
  "website development delhi",
  "website design agency in delhi",
  "best website designing agency in delhi",
  "website designing company in karol bagh delhi",
  "website development companies in delhi ncr",
  "website designing company in dwarka delhi",
  "dynamic website development company in delhi",
  "website design & development company in delhi",
  "website developer in delhi ncr",
  "website designing company in east delhi",
  "web development company in delhi evg software solutions",
  "website designing company in delhi futuregenapps",
  "website development in delhi",
  "best website designing company in janakpuri delhi",
  "web designing company in delhi job",
  "website developer jobs in delhi",
  "website development company in new delhi",
  "shopify website development company in delhi ncr",
  "top website development company in delhi ncr",
  "website designing company in north delhi",
  "website designing company in new delhi",
  "website designing company in delhi near delhi",
  "best ecommerce website development company in new delhi ncr",
  "website designing company in laxmi nagar delhi",
  "website designing company in lajpat nagar delhi",
  "best web development company in delhi ncr",
  "web development company in new delhi",
  "website designing company in delhi with price",
  "webkik services website development and marketing agency in new delhi photos",
  "website designing company in rohini delhi",
  "web circle top website designing company in delhi reviews",
  "kdr soft technologies - website designing company in delhi reviews",
  "webpulse - best website designing company in delhi reviews",
  "website designing company in saket delhi",
  "best website designing company in south delhi",
  "travel website development company in delhi",
  "website designing company in west delhi",
  "top website designing company in delhi with price",
  "best website designing company in west delhi",
  "website development company in mumbai",
  "website development company in mumbai saryu business solutions reviews",
  "website designing agency in mumbai",
  "best website development agency in mumbai",
  "website development company in navi mumbai",
  "best website development company in mumbai",
  "ecommerce website development company in mumbai",
  "wordpress website development company in mumbai",
  "top website development company in mumbai",
  "shopify website development company in mumbai",
  "logistics website development company in mumbai",
  "finance website development company in mumbai",
  "dentist website development company in mumbai",
  "pharmaceutical website development company in mumbai",
  "website development in mumbai",
  "website design agency in mumbai",
  "website development companies in mumbai",
  "fusionlabs digital social media marketing agency & website development company in mumbai",
  "website development mumbai",
  "website designing company in navi mumbai",
  "best website development company in navi mumbai",
  "ecommerce website development company in navi mumbai",
  "top website development company in navi mumbai",
  "website design and development company in navi mumbai",
  "web development agency website template free",
  "website development company website template",
  "website design agency website template",
  "web development company website templates free download",
  "web development company website template wordpress",
  "web development company website template themeforest",
  "web design agency website template free",
  "web development company website template bootstrap free",
  "website design company website template",
  "web design company website template free download",
  "web agency website template",
  "web development agency template",
  "web agency website template free",
  "web agency website template figma",
  "how much do web developers charge to build a website",
  "which website builder has the best templates",
  "website development website template",
  "web development company website template free download",
  "website domain name example",
  "website and domain cost",
  "web developer website examples",
  "website template for web development company",
  "design agency website template framer",
  "design agency website template free download",
  "design agency website template figma",
  "web design agency template framer",
  "design agency website template wordpress",
  "website development company in kolkata",
  "wordpress website development agency in kolkata",
  "website development agency in salt lake kolkata",
  "best website development company in kolkata",
  "ecommerce website development company in kolkata",
  "top website development company in kolkata",
  "wordpress website development company in kolkata",
  "custom website development company in kolkata",
  "softsparrow website development company in kolkata",
  "low cost website development company in kolkata",
  "website and app development company in kolkata",
  "lowest cost website development company in kolkata",
  "top 10 website development company in kolkata",
  "best web development agency in kolkata",
  "web application development agency in kolkata",
  "website development kolkata",
  "web designer salary in kolkata",
  "web developer salary in kolkata",
  "web development company in kolkata for freshers",
  "web development company in kolkata sector v",
  "web development company in kolkata sector - v",
  "website development company in usa",
  "website development company in usa list",
  "website designing agency in usa",
  "best website development company in usa",
  "ecommerce website development company in usa",
  "top website development company in usa",
  "wordpress website development company in usa",
  "shopify website development company in usa",
  "custom website development company in usa",
  "web development agency in usa",
  "website design and development company in usa",
  "web application development agency in usa",
  "top web development agency in usa",
  "website development cost in usa",
  "web development companies in usa",
  "website development in usa",
  "web design companies in usa",
  "web development company in the usa",
  "website development company in us",
  "website development usa",
  "wordpress website development agency london",
  "best website design agency london",
  "creative website design agency london",
  "website development company in uk",
  "web development company in london",
  "website development in uk",
  "website development agency in london",
  "website design agency in london",
  "website design company in london",
  "responsive website design agency in london",
  "best website development company in london",
  "web development agency in london",
  "website designer in london",
  "website development london",
  "london website agency",
  "web design agency london penta",
  "professional wordpress website design agency london uk",
  "web design agency london uk",
  "web development companies in london",
  "web development agency website design",
  "website development company website design",
  "web agency website design",
  "web development agency design",
  "how much do web designers charge for a website",
  "website development website",
  "web design and development job description",
  "difference between web design and development",
  "web design and development agency",
  "website design & development services",
  "how much do web designers make per website",
  "website design services near me",
  "website design agency india",
  "website designing agency in bangalore",
  "website development company in bangalore brandstory",
  "best website development agency in bangalore",
  "best website development company in bangalore",
  "ecommerce website development company in bangalore",
  "wordpress website development company in bangalore",
  "top website development company in bangalore",
  "shopify website development company in bangalore",
  "custom website development company in bangalore",
  "cheap website development company in bangalore",
  "framer website development company in bangalore",
  "magento website development company in bangalore",
  "cms website development company in bangalore",
  "best ecommerce website development company in bangalore",
  "website designing company in bangalore bengaluru karnataka",
  "web development companies in bangalore",
  "top 10 web development companies in bangalore",
  "web development agency in bangalore",
  "website development in bangalore",
  "web designer salary in bangalore",
  "web development company in bangalore for freshers",
  "software development",
  "web development",
  "mobile app development",
  "digital marketing",
  "SaaS",
  "custom software",
  "AI development",
  "machine learning",
  "cloud computing",
  "software development company",
  "web development company",
  "digital marketing agency",
  "software development India",
  "web development India",
  "digital marketing India",
  "software development USA",
  "software development UK",
  "software development Germany",
];

// Page-specific keywords (merged with global defaults automatically)
export const PAGE_SPECIFIC_KEYWORDS: Record<string, string[]> = {
  '/': [
    'MyEnum Agency',
    'software development company',
    'best software development company',
    'custom software development',
    'SaaS development company',
    'web development company India',
    'digital marketing agency India',
  ],
  '/about': [
    'MyEnum Agency about',
    'software development company about',
    'best software development agency',
    'digital marketing agency about',
  ],
  '/services': [
    'software development services',
    'web development services',
    'mobile app development services',
    'digital marketing services',
    'SaaS development services',
    'custom software development services',
  ],
  '/contact': [
    'contact MyEnum Agency',
    'software development company contact',
    'get a quote for software development',
    'digital marketing agency contact',
  ],
  '/germany': [
    'software development Germany',
    'web development Germany',
    'digital marketing Germany',
    'SaaS development Germany',
    'software development company Berlin',
    'software development company Munich',
  ],
  '/karnataka': [
    'software development Karnataka',
    'web development Bangalore',
    'software development company Bangalore',
    'digital marketing Karnataka',
    'SaaS development Bangalore',
  ],
  '/kerala': [
    'software development Kerala',
    'web development Kerala',
    'software development company Kochi',
    'digital marketing Kerala',
    'SaaS development Kerala',
  ],
  '/uk': [
    'software development UK',
    'web development London',
    'software development company London',
    'digital marketing UK',
    'SaaS development UK',
  ],
  '/tamil-nadu': [
    'software development Tamil Nadu',
    'web development Chennai',
    'software development company Salem',
    'digital marketing Tamil Nadu',
    'SaaS development Tamil Nadu',
  ],
  '/features': [
    'software development features',
    'SaaS product features',
    'custom software features',
    'web development features',
  ],
  '/partnership': [
    'software development partnership',
    'digital marketing partnership',
    'technology partner India',
    'SaaS partnership',
  ],
  '/privacy': [
    'MyEnum Agency privacy policy',
    'software development privacy',
    'digital marketing privacy policy',
  ],
  '/terms': [
    'MyEnum Agency terms of service',
    'software development terms',
    'digital marketing terms of service',
  ],
  '/testimonials': [
    'MyEnum Agency reviews',
    'software development testimonials',
    'digital marketing agency reviews',
    'client success stories',
  ],
  '/product': [
    'SaaS products by MyEnum',
    'custom software products',
    'The Doctor Pro clinic software',
    'hospital management system',
    'SaaS product development',
  ],
  '/careers': [
    'MyEnum Agency careers',
    'software development jobs',
    'web development jobs India',
    'digital marketing jobs',
    'remote software development jobs',
  ],
  '/undermaintenance': [
    'MyEnum Agency maintenance',
    'website under maintenance',
  ],
};

// Helper to merge keywords: global defaults + page-specific + any additional keywords
export function getMergedKeywords(pagePath: string, additionalKeywords: string[] = []): string[] {
  const pageSpecific = PAGE_SPECIFIC_KEYWORDS[pagePath] || [];
  return Array.from(new Set([...GLOBAL_DEFAULT_KEYWORDS, ...pageSpecific, ...additionalKeywords]));
}

// Backward compatibility
export const DEFAULT_KEYWORDS = GLOBAL_DEFAULT_KEYWORDS;
